package edu.cornell.kfs.concur;

public class ConcurParameterConstants {

    public static final String CONCUR_AP_PDP_ORIGINATION_CODE = "CONCUR_AP_PDP_ORIGINATION_CODE";
    public static final String CONCUR_SAE_PDP_DOCUMENT_TYPE = "CONCUR_SAE_PDP_DOCUMENT_TYPE";
    public static final String CONCUR_CUSTOMER_PROFILE_GROUP_ID = "CONCUR_CUSTOMER_PROFILE_GROUP_ID";
    public static final String CONCUR_CUSTOMER_PROFILE_LOCATION = "CONCUR_CUSTOMER_PROFILE_LOCATION";
    public static final String CONCUR_CUSTOMER_PROFILE_UNIT = "CONCUR_CUSTOMER_PROFILE_UNIT";
    public static final String CONCUR_CUSTOMER_PROFILE_SUB_UNIT = "CONCUR_CUSTOMER_PROFILE_SUB_UNIT";
    public static final String DEFAULT_TRAVEL_REQUEST_OBJECT_CODE = "DEFAULT_TRAVEL_REQUEST_OBJECT_CODE";
    public static final String CONCUR_PENDING_CLIENT_OBJECT_CODE_OVERRIDE = "CONCUR_PENDING_CLIENT_OBJECT_CODE_OVERRIDE";

}
