package edu.cornell.kfs.concur;

public class ConcurParameterConstants {

    public static final String CONCUR_AP_PDP_ORIGINATION_CODE = "CONCUR_AP_PDP_ORIGINATION_CODE";
    public static final String CONCUR_SAE_PDP_DOCUMENT_TYPE = "CONCUR_SAE_PDP_DOCUMENT_TYPE";
    public static final String CONCUR_CUSTOMER_PROFILE_GROUP_ID = "CONCUR_CUSTOMER_PROFILE_GROUP_ID";
    public static final String CONCUR_CUSTOMER_PROFILE_LOCATION = "CONCUR_CUSTOMER_PROFILE_LOCATION";
    public static final String CONCUR_CUSTOMER_PROFILE_UNIT = "CONCUR_CUSTOMER_PROFILE_UNIT";
    public static final String CONCUR_CUSTOMER_PROFILE_SUB_UNIT = "CONCUR_CUSTOMER_PROFILE_SUB_UNIT";
    public static final String DEFAULT_TRAVEL_REQUEST_OBJECT_CODE = "DEFAULT_TRAVEL_REQUEST_OBJECT_CODE";
    public static final String CONCUR_PENDING_CLIENT_OBJECT_CODE_OVERRIDE = "CONCUR_PENDING_CLIENT_OBJECT_CODE_OVERRIDE";
    public static final String CONCUR_VALID_TRAVELER_STATUSES_FOR_PDP_EMPLOYEE_PROCESSING = "CONCUR_VALID_TRAVELER_STATUSES_FOR_PDP_EMPLOYEE_PROCESSING";

    public static final String CONCUR_PDP_DEFAULT_INVOICE_NUMBER = "CONCUR_PDP_DEFAULT_INVOICE_NUMBER";
    public static final String CONCUR_SAE_PDP_DEFAULT_OBJECT_CODE = "CONCUR_SAE_PDP_DEFAULT_OBJECT_CODE";
    public static final String CONCUR_SAE_COLLECTOR_DOCUMENT_TYPE = "CONCUR_SAE_COLLECTOR_DOCUMENT_TYPE";
    public static final String CONCUR_SAE_COLLECTOR_SYSTEM_ORIGINATION_CODE = "CONCUR_SAE_COLLECTOR_SYSTEM_ORIGINATION_CODE";
    public static final String CONCUR_SAE_COLLECTOR_CHART_CODE = "CONCUR_SAE_COLLECTOR_CHART_CODE";
    public static final String CONCUR_SAE_COLLECTOR_HIGHEST_LEVEL_ORG_CODE = "CONCUR_SAE_COLLECTOR_HIGHEST_LEVEL_ORG_CODE";
    public static final String CONCUR_SAE_COLLECTOR_DEPARTMENT_NAME = "CONCUR_SAE_COLLECTOR_DEPARTMENT_NAME";
    public static final String CONCUR_SAE_COLLECTOR_CAMPUS_CODE = "CONCUR_SAE_COLLECTOR_CAMPUS_CODE";
    public static final String CONCUR_SAE_COLLECTOR_CAMPUS_ADDRESS = "CONCUR_SAE_COLLECTOR_CAMPUS_ADDRESS";
    public static final String CONCUR_SAE_COLLECTOR_NOTIFICATION_CONTACT_EMAIL = "CONCUR_SAE_COLLECTOR_NOTIFICATION_CONTACT_EMAIL";
    public static final String CONCUR_SAE_COLLECTOR_NOTIFICATION_CONTACT_PERSON = "CONCUR_SAE_COLLECTOR_NOTIFICATION_CONTACT_PERSON";
    public static final String CONCUR_SAE_COLLECTOR_NOTIFICATION_CONTACT_PHONE = "CONCUR_SAE_COLLECTOR_NOTIFICATION_CONTACT_PHONE";
    public static final String CONCUR_SAE_COLLECTOR_PREPAID_OFFSET_CHART_CODE = "CONCUR_SAE_COLLECTOR_PREPAID_OFFSET_CHART_CODE";
    public static final String CONCUR_SAE_COLLECTOR_PREPAID_OFFSET_ACCOUNT_NUMBER = "CONCUR_SAE_COLLECTOR_PREPAID_OFFSET_ACCOUNT_NUMBER";
    public static final String CONCUR_SAE_COLLECTOR_PREPAID_OFFSET_OBJECT_CODE = "CONCUR_SAE_COLLECTOR_PREPAID_OFFSET_OBJECT_CODE";
    public static final String CONCUR_SAE_COLLECTOR_PAYMENT_OFFSET_OBJECT_CODE = "CONCUR_SAE_COLLECTOR_PAYMENT_OFFSET_OBJECT_CODE";
    public static final String CONCUR_SAE_COLLECTOR_PERSONAL_OFFSET_OBJECT_CODE = "CONCUR_SAE_COLLECTOR_PERSONAL_OFFSET_OBJECT_CODE";
    public static final String CONCUR_SAE_COLLECTOR_ATM_FEE_DEBIT_CHART_CODE = "CONCUR_SAE_COLLECTOR_ATM_FEE_DEBIT_CHART_CODE";
    public static final String CONCUR_SAE_COLLECTOR_ATM_FEE_DEBIT_ACCOUNT_NUMBER = "CONCUR_SAE_COLLECTOR_ATM_FEE_DEBIT_ACCOUNT_NUMBER";
    public static final String CONCUR_SAE_COLLECTOR_ATM_FEE_DEBIT_OBJECT_CODE = "CONCUR_SAE_COLLECTOR_ATM_FEE_DEBIT_OBJECT_CODE";
    public static final String CONCUR_SAE_COLLECTOR_UNUSED_ATM_OFFSET_OBJECT_CODE = "CONCUR_SAE_COLLECTOR_UNUSED_ATM_OFFSET_OBJECT_CODE";

    public static final String CONCUR_REQUEST_EXTRACT_PDP_DOCUMENT_TYPE = "CONCUR_REQUEST_EXTRACT_PDP_DOCUMENT_TYPE";
    public static final String CONCUR_PROCESS_CASH_ADVANCES_FROM_SAE_DATA_IND = "CONCUR_PROCESS_CASH_ADVANCES_FROM_SAE_DATA_IND";
    public static final String CONCUR_CASH_ADVANCE_PDP_DOCUMENT_TYPE = "CONCUR_CASH_ADVANCE_PDP_DOCUMENT_TYPE";
    public static final String DEFAULT_CONCUR_VALID_TRAVELER_STATUS_FOR_PDP_EMPLOYEE_CASH_ADVANCE_PROCESSING = "DEFAULT_CONCUR_VALID_TRAVELER_STATUS_FOR_PDP_EMPLOYEE_CASH_ADVANCE_PROCESSING";
    
    public static final String CONCUR_PROCESS_FAILED_EVENT_QUEUE = "CONCUR_PROCESS_FAILED_EVENT_QUEUE";
    public static final String CONCUR_REFRESH_ACCESS_TOKEN = "CONCUR_REFRESH_ACCESS_TOKEN";
    
    public static final String CONCUR_REPORT_EMAIL_FROM_ADDRESS = "CONCUR_REPORT_EMAIL_FROM_ADDRESS";
    public static final String CONCUR_REPORT_EMAIL_TO_ADDRESS = "CONCUR_REPORT_EMAIL_TO_ADDRESS";
    
    public static final String WEBSERVICE_MAX_RETRIES = "WEBSERVICE_MAX_RETRIES";
    public static final String CONCUR_ACCESS_TOKEN_ENDPOINT = "CONCUR_ACCESS_TOKEN_ENDPOINT";
    public static final String EXPENSE_V3_LISTING_ENDPOINT = "EXPENSE_V3_LISTING_ENDPOINT";
    public static final String EXPENSE_V3_REPORT_ENDPOINT = "EXPENSE_V3_REPORT_ENDPOINT";
    public static final String CONCUR_OAUTH2_REPLACE_REQUEST_TOKEN_INSTRUCTIONS = "CONCUR_OAUTH2_REPLACE_REQUEST_TOKEN_INSTRUCTIONS";
    public static final String EXPENSE_V3_ALLOCATION_ENDPOINT = "EXPENSE_V3_ALLOCATION_ENDPOINT";
    public static final String REQUEST_V4_REQUESTS_ENDPOINT = "REQUEST_V4_REQUESTS_ENDPOINT";
    public static final String REQUEST_V4_QUERY_PAGE_SIZE = "REQUEST_V4_QUERY_PAGE_SIZE";
    public static final String REQUEST_V4_QUERY_FROM_DATE_OVERRIDE = "REQUEST_V4_QUERY_FROM_DATE_OVERRIDE";
    public static final String REQUEST_V4_QUERY_TO_DATE_OVERRIDE = "REQUEST_V4_QUERY_TO_DATE_OVERRIDE";
    public static final String REQUEST_V4_TEST_APPROVERS = "REQUEST_V4_TEST_APPROVERS";

}
