package edu.cornell.kfs.concur;

public class ConcurKeyConstants {
    public static final String CONCUR_ACCOUNT_INFO_IS_REQUIRED = "error.concur.account.info.required";
    public static final String INCORRECT_CONCUR_STATUS_CODE = "error.concur.status.invalid";

    // TODO: Move these to ConcurParameterConstants once that class exists!
    public static final String SAE_COLLECTOR_DOCTYPE_CODE = "CONCUR_SAE_COLLECTOR_DOCTYPE_CODE";
    public static final String SAE_COLLECTOR_SYSTEM_ORIGINATION_CODE = "CONCUR_SAE_COLLECTOR_SYSTEM_ORIGINATION_CODE";
    public static final String SAE_COLLECTOR_CHART_CODE = "CONCUR_SAE_COLLECTOR_CHART_CODE";
    public static final String SAE_COLLECTOR_HIGHEST_LEVEL_ORG_CODE = "CONCUR_SAE_COLLECTOR_HIGHEST_LEVEL_ORG_CODE";
    public static final String SAE_COLLECTOR_UNDEFINED_OBJECT_CODE = "CONCUR_SAE_COLLECTOR_UNDEFINED_OBJECT_CODE";
    public static final String SAE_COLLECTOR_DEFAULT_OBJECT_CODE = "CONCUR_SAE_COLLECTOR_DEFAULT_OBJECT_CODE";
    public static final String SAE_COLLECTOR_DEPARTMENT_NAME = "CONCUR_SAE_COLLECTOR_DEPARTMENT_NAME";
    public static final String SAE_COLLECTOR_CAMPUS_CODE = "CONCUR_SAE_COLLECTOR_CAMPUS_CODE";
    public static final String SAE_COLLECTOR_CAMPUS_ADDRESS = "CONCUR_SAE_COLLECTOR_CAMPUS_ADDRESS";
    public static final String SAE_COLLECTOR_NOTIFICATION_CONTACT_EMAIL = "CONCUR_SAE_COLLECTOR_NOTIFICATION_CONTACT_EMAIL";
    public static final String SAE_COLLECTOR_NOTIFICATION_CONTACT_PERSON = "CONCUR_SAE_COLLECTOR_NOTIFICATION_CONTACT_PERSON";
    public static final String SAE_COLLECTOR_NOTIFICATION_CONTACT_PHONE = "CONCUR_SAE_COLLECTOR_NOTIFICATION_CONTACT_PHONE";
}
