//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.14 at 07:50:06 AM EST 
//


package edu.cornell.kfs.module.purap.jaggaer.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.cornell.kfs.module.purap.jaggaer.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.cornell.kfs.module.purap.jaggaer.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BankName }
     * 
     */
    public BankName createBankName() {
        return new BankName();
    }

    /**
     * Create an instance of {@link LocationEffectiveDate }
     * 
     */
    public LocationEffectiveDate createLocationEffectiveDate() {
        return new LocationEffectiveDate();
    }

    /**
     * Create an instance of {@link InternalName }
     * 
     */
    public InternalName createInternalName() {
        return new InternalName();
    }

    /**
     * Create an instance of {@link TaxInformationList }
     * 
     */
    public TaxInformationList createTaxInformationList() {
        return new TaxInformationList();
    }

    /**
     * Create an instance of {@link TaxInformation }
     * 
     */
    public TaxInformation createTaxInformation() {
        return new TaxInformation();
    }

    /**
     * Create an instance of {@link ServiceAreaInternalName }
     * 
     */
    public ServiceAreaInternalName createServiceAreaInternalName() {
        return new ServiceAreaInternalName();
    }

    /**
     * Create an instance of {@link TermsType }
     * 
     */
    public TermsType createTermsType() {
        return new TermsType();
    }

    /**
     * Create an instance of {@link YearEstablished }
     * 
     */
    public YearEstablished createYearEstablished() {
        return new YearEstablished();
    }

    /**
     * Create an instance of {@link IsoCurrencyCode }
     * 
     */
    public IsoCurrencyCode createIsoCurrencyCode() {
        return new IsoCurrencyCode();
    }

    /**
     * Create an instance of {@link FlexFields }
     * 
     */
    public FlexFields createFlexFields() {
        return new FlexFields();
    }

    /**
     * Create an instance of {@link FlexField1 }
     * 
     */
    public FlexField1 createFlexField1() {
        return new FlexField1();
    }

    /**
     * Create an instance of {@link FlexField2 }
     * 
     */
    public FlexField2 createFlexField2() {
        return new FlexField2();
    }

    /**
     * Create an instance of {@link FlexField3 }
     * 
     */
    public FlexField3 createFlexField3() {
        return new FlexField3();
    }

    /**
     * Create an instance of {@link FlexField4 }
     * 
     */
    public FlexField4 createFlexField4() {
        return new FlexField4();
    }

    /**
     * Create an instance of {@link FlexField5 }
     * 
     */
    public FlexField5 createFlexField5() {
        return new FlexField5();
    }

    /**
     * Create an instance of {@link AnnualSalesList }
     * 
     */
    public AnnualSalesList createAnnualSalesList() {
        return new AnnualSalesList();
    }

    /**
     * Create an instance of {@link AnnualSales }
     * 
     */
    public AnnualSales createAnnualSales() {
        return new AnnualSales();
    }

    /**
     * Create an instance of {@link CommodityCodeList }
     * 
     */
    public CommodityCodeList createCommodityCodeList() {
        return new CommodityCodeList();
    }

    /**
     * Create an instance of {@link CommodityCode }
     * 
     */
    public CommodityCode createCommodityCode() {
        return new CommodityCode();
    }

    /**
     * Create an instance of {@link StateServiceAreaInternalName }
     * 
     */
    public StateServiceAreaInternalName createStateServiceAreaInternalName() {
        return new StateServiceAreaInternalName();
    }

    /**
     * Create an instance of {@link ServiceAreaList }
     * 
     */
    public ServiceAreaList createServiceAreaList() {
        return new ServiceAreaList();
    }

    /**
     * Create an instance of {@link ServiceArea }
     * 
     */
    public ServiceArea createServiceArea() {
        return new ServiceArea();
    }

    /**
     * Create an instance of {@link DiscountPercent }
     * 
     */
    public DiscountPercent createDiscountPercent() {
        return new DiscountPercent();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link Errors }
     * 
     */
    public Errors createErrors() {
        return new Errors();
    }

    /**
     * Create an instance of {@link DiversityCertificate }
     * 
     */
    public DiversityCertificate createDiversityCertificate() {
        return new DiversityCertificate();
    }

    /**
     * Create an instance of {@link Attachments }
     * 
     */
    public Attachments createAttachments() {
        return new Attachments();
    }

    /**
     * Create an instance of {@link Tax2 }
     * 
     */
    public Tax2 createTax2() {
        return new Tax2();
    }

    /**
     * Create an instance of {@link Tax1 }
     * 
     */
    public Tax1 createTax1() {
        return new Tax1();
    }

    /**
     * Create an instance of {@link InsuranceLimit }
     * 
     */
    public InsuranceLimit createInsuranceLimit() {
        return new InsuranceLimit();
    }

    /**
     * Create an instance of {@link ERPNumber }
     * 
     */
    public ERPNumber createERPNumber() {
        return new ERPNumber();
    }

    /**
     * Create an instance of {@link DiscountAmount }
     * 
     */
    public DiscountAmount createDiscountAmount() {
        return new DiscountAmount();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Authentication }
     * 
     */
    public Authentication createAuthentication() {
        return new Authentication();
    }

    /**
     * Create an instance of {@link DUNS }
     * 
     */
    public DUNS createDUNS() {
        return new DUNS();
    }

    /**
     * Create an instance of {@link SupplierErrors }
     * 
     */
    public SupplierErrors createSupplierErrors() {
        return new SupplierErrors();
    }

    /**
     * Create an instance of {@link SupplierRef }
     * 
     */
    public SupplierRef createSupplierRef() {
        return new SupplierRef();
    }

    /**
     * Create an instance of {@link ErrorMessage }
     * 
     */
    public ErrorMessage createErrorMessage() {
        return new ErrorMessage();
    }

    /**
     * Create an instance of {@link AddressErrors }
     * 
     */
    public AddressErrors createAddressErrors() {
        return new AddressErrors();
    }

    /**
     * Create an instance of {@link ContactErrors }
     * 
     */
    public ContactErrors createContactErrors() {
        return new ContactErrors();
    }

    /**
     * Create an instance of {@link LocationErrors }
     * 
     */
    public LocationErrors createLocationErrors() {
        return new LocationErrors();
    }

    /**
     * Create an instance of {@link AccountsPayableErrors }
     * 
     */
    public AccountsPayableErrors createAccountsPayableErrors() {
        return new AccountsPayableErrors();
    }

    /**
     * Create an instance of {@link CustomElementErrors }
     * 
     */
    public CustomElementErrors createCustomElementErrors() {
        return new CustomElementErrors();
    }

    /**
     * Create an instance of {@link CustomElementIdentifier }
     * 
     */
    public CustomElementIdentifier createCustomElementIdentifier() {
        return new CustomElementIdentifier();
    }

    /**
     * Create an instance of {@link RegistrationProfileType }
     * 
     */
    public RegistrationProfileType createRegistrationProfileType() {
        return new RegistrationProfileType();
    }

    /**
     * Create an instance of {@link NumberOfEmployees }
     * 
     */
    public NumberOfEmployees createNumberOfEmployees() {
        return new NumberOfEmployees();
    }

    /**
     * Create an instance of {@link SupplierCapital }
     * 
     */
    public SupplierCapital createSupplierCapital() {
        return new SupplierCapital();
    }

    /**
     * Create an instance of {@link Amount }
     * 
     */
    public Amount createAmount() {
        return new Amount();
    }

    /**
     * Create an instance of {@link Days }
     * 
     */
    public Days createDays() {
        return new Days();
    }

    /**
     * Create an instance of {@link WebSiteURL }
     * 
     */
    public WebSiteURL createWebSiteURL() {
        return new WebSiteURL();
    }

    /**
     * Create an instance of {@link CustomElementList }
     * 
     */
    public CustomElementList createCustomElementList() {
        return new CustomElementList();
    }

    /**
     * Create an instance of {@link CustomElement }
     * 
     */
    public CustomElement createCustomElement() {
        return new CustomElement();
    }

    /**
     * Create an instance of {@link LocationList }
     * 
     */
    public LocationList createLocationList() {
        return new LocationList();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link TaxShipping }
     * 
     */
    public TaxShipping createTaxShipping() {
        return new TaxShipping();
    }

    /**
     * Create an instance of {@link FirstName }
     * 
     */
    public FirstName createFirstName() {
        return new FirstName();
    }

    /**
     * Create an instance of {@link BankAccount }
     * 
     */
    public BankAccount createBankAccount() {
        return new BankAccount();
    }

    /**
     * Create an instance of {@link AccountHoldersName }
     * 
     */
    public AccountHoldersName createAccountHoldersName() {
        return new AccountHoldersName();
    }

    /**
     * Create an instance of {@link AccountNumberType }
     * 
     */
    public AccountNumberType createAccountNumberType() {
        return new AccountNumberType();
    }

    /**
     * Create an instance of {@link RoutingNumber }
     * 
     */
    public RoutingNumber createRoutingNumber() {
        return new RoutingNumber();
    }

    /**
     * Create an instance of {@link BankAccountNumber }
     * 
     */
    public BankAccountNumber createBankAccountNumber() {
        return new BankAccountNumber();
    }

    /**
     * Create an instance of {@link IbanBankAccountNumber }
     * 
     */
    public IbanBankAccountNumber createIbanBankAccountNumber() {
        return new IbanBankAccountNumber();
    }

    /**
     * Create an instance of {@link DirectDepositFormat }
     * 
     */
    public DirectDepositFormat createDirectDepositFormat() {
        return new DirectDepositFormat();
    }

    /**
     * Create an instance of {@link BankIdentifierCode }
     * 
     */
    public BankIdentifierCode createBankIdentifierCode() {
        return new BankIdentifierCode();
    }

    /**
     * Create an instance of {@link InternationalRoutingCode }
     * 
     */
    public InternationalRoutingCode createInternationalRoutingCode() {
        return new InternationalRoutingCode();
    }

    /**
     * Create an instance of {@link IsoCountryCode }
     * 
     */
    public IsoCountryCode createIsoCountryCode() {
        return new IsoCountryCode();
    }

    /**
     * Create an instance of {@link AddressLine1 }
     * 
     */
    public AddressLine1 createAddressLine1() {
        return new AddressLine1();
    }

    /**
     * Create an instance of {@link AddressLine2 }
     * 
     */
    public AddressLine2 createAddressLine2() {
        return new AddressLine2();
    }

    /**
     * Create an instance of {@link AddressLine3 }
     * 
     */
    public AddressLine3 createAddressLine3() {
        return new AddressLine3();
    }

    /**
     * Create an instance of {@link City }
     * 
     */
    public City createCity() {
        return new City();
    }

    /**
     * Create an instance of {@link State }
     * 
     */
    public State createState() {
        return new State();
    }

    /**
     * Create an instance of {@link PostalCode }
     * 
     */
    public PostalCode createPostalCode() {
        return new PostalCode();
    }

    /**
     * Create an instance of {@link PONumberSelection }
     * 
     */
    public PONumberSelection createPONumberSelection() {
        return new PONumberSelection();
    }

    /**
     * Create an instance of {@link NumberWheel }
     * 
     */
    public NumberWheel createNumberWheel() {
        return new NumberWheel();
    }

    /**
     * Create an instance of {@link TollFreePhone }
     * 
     */
    public TollFreePhone createTollFreePhone() {
        return new TollFreePhone();
    }

    /**
     * Create an instance of {@link TelephoneNumber }
     * 
     */
    public TelephoneNumber createTelephoneNumber() {
        return new TelephoneNumber();
    }

    /**
     * Create an instance of {@link SupplierRegSeat }
     * 
     */
    public SupplierRegSeat createSupplierRegSeat() {
        return new SupplierRegSeat();
    }

    /**
     * Create an instance of {@link CustomPaymentTerm }
     * 
     */
    public CustomPaymentTerm createCustomPaymentTerm() {
        return new CustomPaymentTerm();
    }

    /**
     * Create an instance of {@link InsuranceInformation }
     * 
     */
    public InsuranceInformation createInsuranceInformation() {
        return new InsuranceInformation();
    }

    /**
     * Create an instance of {@link PolicyNumber }
     * 
     */
    public PolicyNumber createPolicyNumber() {
        return new PolicyNumber();
    }

    /**
     * Create an instance of {@link ExpirationDate }
     * 
     */
    public ExpirationDate createExpirationDate() {
        return new ExpirationDate();
    }

    /**
     * Create an instance of {@link InsuranceProvider }
     * 
     */
    public InsuranceProvider createInsuranceProvider() {
        return new InsuranceProvider();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link InsuranceProviderPhone }
     * 
     */
    public InsuranceProviderPhone createInsuranceProviderPhone() {
        return new InsuranceProviderPhone();
    }

    /**
     * Create an instance of {@link InsuranceCertificate }
     * 
     */
    public InsuranceCertificate createInsuranceCertificate() {
        return new InsuranceCertificate();
    }

    /**
     * Create an instance of {@link OtherTypeName }
     * 
     */
    public OtherTypeName createOtherTypeName() {
        return new OtherTypeName();
    }

    /**
     * Create an instance of {@link Email }
     * 
     */
    public Email createEmail() {
        return new Email();
    }

    /**
     * Create an instance of {@link AccountId }
     * 
     */
    public AccountId createAccountId() {
        return new AccountId();
    }

    /**
     * Create an instance of {@link LookupErrorMessage }
     * 
     */
    public LookupErrorMessage createLookupErrorMessage() {
        return new LookupErrorMessage();
    }

    /**
     * Create an instance of {@link CountryOfOrigin }
     * 
     */
    public CountryOfOrigin createCountryOfOrigin() {
        return new CountryOfOrigin();
    }

    /**
     * Create an instance of {@link Attachment }
     * 
     */
    public Attachment createAttachment() {
        return new Attachment();
    }

    /**
     * Create an instance of {@link XopInclude }
     * 
     */
    public XopInclude createXopInclude() {
        return new XopInclude();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link LookupErrors }
     * 
     */
    public LookupErrors createLookupErrors() {
        return new LookupErrors();
    }

    /**
     * Create an instance of {@link Tax1Active }
     * 
     */
    public Tax1Active createTax1Active() {
        return new Tax1Active();
    }

    /**
     * Create an instance of {@link FOB }
     * 
     */
    public FOB createFOB() {
        return new FOB();
    }

    /**
     * Create an instance of {@link SecondaryNaics }
     * 
     */
    public SecondaryNaics createSecondaryNaics() {
        return new SecondaryNaics();
    }

    /**
     * Create an instance of {@link TaxIdentificationNumber }
     * 
     */
    public TaxIdentificationNumber createTaxIdentificationNumber() {
        return new TaxIdentificationNumber();
    }

    /**
     * Create an instance of {@link SupplierKeywords }
     * 
     */
    public SupplierKeywords createSupplierKeywords() {
        return new SupplierKeywords();
    }

    /**
     * Create an instance of {@link AdditionalData }
     * 
     */
    public AdditionalData createAdditionalData() {
        return new AdditionalData();
    }

    /**
     * Create an instance of {@link AccountsPayable }
     * 
     */
    public AccountsPayable createAccountsPayable() {
        return new AccountsPayable();
    }

    /**
     * Create an instance of {@link SQIntegrationNumber }
     * 
     */
    public SQIntegrationNumber createSQIntegrationNumber() {
        return new SQIntegrationNumber();
    }

    /**
     * Create an instance of {@link ThirdPartyRefNumber }
     * 
     */
    public ThirdPartyRefNumber createThirdPartyRefNumber() {
        return new ThirdPartyRefNumber();
    }

    /**
     * Create an instance of {@link Active }
     * 
     */
    public Active createActive() {
        return new Active();
    }

    /**
     * Create an instance of {@link AssociatedAddress }
     * 
     */
    public AssociatedAddress createAssociatedAddress() {
        return new AssociatedAddress();
    }

    /**
     * Create an instance of {@link ContactName }
     * 
     */
    public ContactName createContactName() {
        return new ContactName();
    }

    /**
     * Create an instance of {@link Purpose }
     * 
     */
    public Purpose createPurpose() {
        return new Purpose();
    }

    /**
     * Create an instance of {@link AccountHolderName }
     * 
     */
    public AccountHolderName createAccountHolderName() {
        return new AccountHolderName();
    }

    /**
     * Create an instance of {@link AccountType }
     * 
     */
    public AccountType createAccountType() {
        return new AccountType();
    }

    /**
     * Create an instance of {@link CountryCode }
     * 
     */
    public CountryCode createCountryCode() {
        return new CountryCode();
    }

    /**
     * Create an instance of {@link SupplierTaxRepresentativeId }
     * 
     */
    public SupplierTaxRepresentativeId createSupplierTaxRepresentativeId() {
        return new SupplierTaxRepresentativeId();
    }

    /**
     * Create an instance of {@link SIC }
     * 
     */
    public SIC createSIC() {
        return new SIC();
    }

    /**
     * Create an instance of {@link AccountsPayableList }
     * 
     */
    public AccountsPayableList createAccountsPayableList() {
        return new AccountsPayableList();
    }

    /**
     * Create an instance of {@link AssignedBusinessUnitsList }
     * 
     */
    public AssignedBusinessUnitsList createAssignedBusinessUnitsList() {
        return new AssignedBusinessUnitsList();
    }

    /**
     * Create an instance of {@link BusinessUnitInternalName }
     * 
     */
    public BusinessUnitInternalName createBusinessUnitInternalName() {
        return new BusinessUnitInternalName();
    }

    /**
     * Create an instance of {@link Brand }
     * 
     */
    public Brand createBrand() {
        return new Brand();
    }

    /**
     * Create an instance of {@link AssociatedContactList }
     * 
     */
    public AssociatedContactList createAssociatedContactList() {
        return new AssociatedContactList();
    }

    /**
     * Create an instance of {@link AssociatedContact }
     * 
     */
    public AssociatedContact createAssociatedContact() {
        return new AssociatedContact();
    }

    /**
     * Create an instance of {@link StateServiceAreaList }
     * 
     */
    public StateServiceAreaList createStateServiceAreaList() {
        return new StateServiceAreaList();
    }

    /**
     * Create an instance of {@link AnnualSalesYear }
     * 
     */
    public AnnualSalesYear createAnnualSalesYear() {
        return new AnnualSalesYear();
    }

    /**
     * Create an instance of {@link AreaCode }
     * 
     */
    public AreaCode createAreaCode() {
        return new AreaCode();
    }

    /**
     * Create an instance of {@link LastName }
     * 
     */
    public LastName createLastName() {
        return new LastName();
    }

    /**
     * Create an instance of {@link AccountsPayableRef }
     * 
     */
    public AccountsPayableRef createAccountsPayableRef() {
        return new AccountsPayableRef();
    }

    /**
     * Create an instance of {@link FeeType }
     * 
     */
    public FeeType createFeeType() {
        return new FeeType();
    }

    /**
     * Create an instance of {@link OtherNames }
     * 
     */
    public OtherNames createOtherNames() {
        return new OtherNames();
    }

    /**
     * Create an instance of {@link PaymentTerms }
     * 
     */
    public PaymentTerms createPaymentTerms() {
        return new PaymentTerms();
    }

    /**
     * Create an instance of {@link Discount }
     * 
     */
    public Discount createDiscount() {
        return new Discount();
    }

    /**
     * Create an instance of {@link Net }
     * 
     */
    public Net createNet() {
        return new Net();
    }

    /**
     * Create an instance of {@link StandardPaymentTermsCode }
     * 
     */
    public StandardPaymentTermsCode createStandardPaymentTermsCode() {
        return new StandardPaymentTermsCode();
    }

    /**
     * Create an instance of {@link DaysAfter }
     * 
     */
    public DaysAfter createDaysAfter() {
        return new DaysAfter();
    }

    /**
     * Create an instance of {@link ClassificationList }
     * 
     */
    public ClassificationList createClassificationList() {
        return new ClassificationList();
    }

    /**
     * Create an instance of {@link Classification }
     * 
     */
    public Classification createClassification() {
        return new Classification();
    }

    /**
     * Create an instance of {@link Tax2Active }
     * 
     */
    public Tax2Active createTax2Active() {
        return new Tax2Active();
    }

    /**
     * Create an instance of {@link TaxDocumentName }
     * 
     */
    public TaxDocumentName createTaxDocumentName() {
        return new TaxDocumentName();
    }

    /**
     * Create an instance of {@link TaxDocumentYear }
     * 
     */
    public TaxDocumentYear createTaxDocumentYear() {
        return new TaxDocumentYear();
    }

    /**
     * Create an instance of {@link TaxDocument }
     * 
     */
    public TaxDocument createTaxDocument() {
        return new TaxDocument();
    }

    /**
     * Create an instance of {@link RequireCardSecurityCode }
     * 
     */
    public RequireCardSecurityCode createRequireCardSecurityCode() {
        return new RequireCardSecurityCode();
    }

    /**
     * Create an instance of {@link Number }
     * 
     */
    public Number createNumber() {
        return new Number();
    }

    /**
     * Create an instance of {@link Shipping }
     * 
     */
    public Shipping createShipping() {
        return new Shipping();
    }

    /**
     * Create an instance of {@link SurchargeConfiguration }
     * 
     */
    public SurchargeConfiguration createSurchargeConfiguration() {
        return new SurchargeConfiguration();
    }

    /**
     * Create an instance of {@link DD214Certificate }
     * 
     */
    public DD214Certificate createDD214Certificate() {
        return new DD214Certificate();
    }

    /**
     * Create an instance of {@link BlanketPONumber }
     * 
     */
    public BlanketPONumber createBlanketPONumber() {
        return new BlanketPONumber();
    }

    /**
     * Create an instance of {@link Notes }
     * 
     */
    public Notes createNotes() {
        return new Notes();
    }

    /**
     * Create an instance of {@link AddressRef }
     * 
     */
    public AddressRef createAddressRef() {
        return new AddressRef();
    }

    /**
     * Create an instance of {@link SecondaryNaicsList }
     * 
     */
    public SecondaryNaicsList createSecondaryNaicsList() {
        return new SecondaryNaicsList();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link PrefPurchaseOrderDeliveryMethod }
     * 
     */
    public PrefPurchaseOrderDeliveryMethod createPrefPurchaseOrderDeliveryMethod() {
        return new PrefPurchaseOrderDeliveryMethod();
    }

    /**
     * Create an instance of {@link Fax }
     * 
     */
    public Fax createFax() {
        return new Fax();
    }

    /**
     * Create an instance of {@link BusinessUnitVendorNumberList }
     * 
     */
    public BusinessUnitVendorNumberList createBusinessUnitVendorNumberList() {
        return new BusinessUnitVendorNumberList();
    }

    /**
     * Create an instance of {@link BusinessUnitVendorNumber }
     * 
     */
    public BusinessUnitVendorNumber createBusinessUnitVendorNumber() {
        return new BusinessUnitVendorNumber();
    }

    /**
     * Create an instance of {@link ExemptFromBackupWithholding }
     * 
     */
    public ExemptFromBackupWithholding createExemptFromBackupWithholding() {
        return new ExemptFromBackupWithholding();
    }

    /**
     * Create an instance of {@link Extension }
     * 
     */
    public Extension createExtension() {
        return new Extension();
    }

    /**
     * Create an instance of {@link Brands }
     * 
     */
    public Brands createBrands() {
        return new Brands();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link LocationActive }
     * 
     */
    public LocationActive createLocationActive() {
        return new LocationActive();
    }

    /**
     * Create an instance of {@link Primary }
     * 
     */
    public Primary createPrimary() {
        return new Primary();
    }

    /**
     * Create an instance of {@link PaymentMethod }
     * 
     */
    public PaymentMethod createPaymentMethod() {
        return new PaymentMethod();
    }

    /**
     * Create an instance of {@link Handling }
     * 
     */
    public Handling createHandling() {
        return new Handling();
    }

    /**
     * Create an instance of {@link TaxInfo }
     * 
     */
    public TaxInfo createTaxInfo() {
        return new TaxInfo();
    }

    /**
     * Create an instance of {@link TermsAndCondition }
     * 
     */
    public TermsAndCondition createTermsAndCondition() {
        return new TermsAndCondition();
    }

    /**
     * Create an instance of {@link OrderDistributionList }
     * 
     */
    public OrderDistributionList createOrderDistributionList() {
        return new OrderDistributionList();
    }

    /**
     * Create an instance of {@link AssociatedAddressList }
     * 
     */
    public AssociatedAddressList createAssociatedAddressList() {
        return new AssociatedAddressList();
    }

    /**
     * Create an instance of {@link SupplierShareholders }
     * 
     */
    public SupplierShareholders createSupplierShareholders() {
        return new SupplierShareholders();
    }

    /**
     * Create an instance of {@link LookupStatus }
     * 
     */
    public LookupStatus createLookupStatus() {
        return new LookupStatus();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Phone }
     * 
     */
    public Phone createPhone() {
        return new Phone();
    }

    /**
     * Create an instance of {@link BlanketPOPaymentMethod }
     * 
     */
    public BlanketPOPaymentMethod createBlanketPOPaymentMethod() {
        return new BlanketPOPaymentMethod();
    }

    /**
     * Create an instance of {@link DoingBusinessAs }
     * 
     */
    public DoingBusinessAs createDoingBusinessAs() {
        return new DoingBusinessAs();
    }

    /**
     * Create an instance of {@link JPMorganVCardPayment }
     * 
     */
    public JPMorganVCardPayment createJPMorganVCardPayment() {
        return new JPMorganVCardPayment();
    }

    /**
     * Create an instance of {@link DisplayName }
     * 
     */
    public DisplayName createDisplayName() {
        return new DisplayName();
    }

    /**
     * Create an instance of {@link CustomElementValueList }
     * 
     */
    public CustomElementValueList createCustomElementValueList() {
        return new CustomElementValueList();
    }

    /**
     * Create an instance of {@link FeeScope }
     * 
     */
    public FeeScope createFeeScope() {
        return new FeeScope();
    }

    /**
     * Create an instance of {@link RestrictFulfillmentLocationsByBusinessUnit }
     * 
     */
    public RestrictFulfillmentLocationsByBusinessUnit createRestrictFulfillmentLocationsByBusinessUnit() {
        return new RestrictFulfillmentLocationsByBusinessUnit();
    }

    /**
     * Create an instance of {@link TaxableByDefault }
     * 
     */
    public TaxableByDefault createTaxableByDefault() {
        return new TaxableByDefault();
    }

    /**
     * Create an instance of {@link TaxHandling }
     * 
     */
    public TaxHandling createTaxHandling() {
        return new TaxHandling();
    }

    /**
     * Create an instance of {@link VatIdentificationNumber }
     * 
     */
    public VatIdentificationNumber createVatIdentificationNumber() {
        return new VatIdentificationNumber();
    }

    /**
     * Create an instance of {@link Fee }
     * 
     */
    public Fee createFee() {
        return new Fee();
    }

    /**
     * Create an instance of {@link UseOrderThreshold }
     * 
     */
    public UseOrderThreshold createUseOrderThreshold() {
        return new UseOrderThreshold();
    }

    /**
     * Create an instance of {@link OrderThreshold }
     * 
     */
    public OrderThreshold createOrderThreshold() {
        return new OrderThreshold();
    }

    /**
     * Create an instance of {@link SupplierRequestMessage }
     * 
     */
    public SupplierRequestMessage createSupplierRequestMessage() {
        return new SupplierRequestMessage();
    }

    /**
     * Create an instance of {@link Supplier }
     * 
     */
    public Supplier createSupplier() {
        return new Supplier();
    }

    /**
     * Create an instance of {@link LookupResponseMessage }
     * 
     */
    public LookupResponseMessage createLookupResponseMessage() {
        return new LookupResponseMessage();
    }

    /**
     * Create an instance of {@link SupplierList }
     * 
     */
    public SupplierList createSupplierList() {
        return new SupplierList();
    }

    /**
     * Create an instance of {@link ParentSupplier }
     * 
     */
    public ParentSupplier createParentSupplier() {
        return new ParentSupplier();
    }

    /**
     * Create an instance of {@link POPaymentMethod }
     * 
     */
    public POPaymentMethod createPOPaymentMethod() {
        return new POPaymentMethod();
    }

    /**
     * Create an instance of {@link POPayment }
     * 
     */
    public POPayment createPOPayment() {
        return new POPayment();
    }

    /**
     * Create an instance of {@link PCardPayment }
     * 
     */
    public PCardPayment createPCardPayment() {
        return new PCardPayment();
    }

    /**
     * Create an instance of {@link DiversityClassification }
     * 
     */
    public DiversityClassification createDiversityClassification() {
        return new DiversityClassification();
    }

    /**
     * Create an instance of {@link AdditionalDataList }
     * 
     */
    public AdditionalDataList createAdditionalDataList() {
        return new AdditionalDataList();
    }

    /**
     * Create an instance of {@link PrimaryNaics }
     * 
     */
    public PrimaryNaics createPrimaryNaics() {
        return new PrimaryNaics();
    }

    /**
     * Create an instance of {@link AllowFreeForm }
     * 
     */
    public AllowFreeForm createAllowFreeForm() {
        return new AllowFreeForm();
    }

    /**
     * Create an instance of {@link NaicsCodes }
     * 
     */
    public NaicsCodes createNaicsCodes() {
        return new NaicsCodes();
    }

    /**
     * Create an instance of {@link PrimaryContactList }
     * 
     */
    public PrimaryContactList createPrimaryContactList() {
        return new PrimaryContactList();
    }

    /**
     * Create an instance of {@link CustomElementValue }
     * 
     */
    public CustomElementValue createCustomElementValue() {
        return new CustomElementValue();
    }

    /**
     * Create an instance of {@link AnnualSalesAmount }
     * 
     */
    public AnnualSalesAmount createAnnualSalesAmount() {
        return new AnnualSalesAmount();
    }

    /**
     * Create an instance of {@link AustinTetra }
     * 
     */
    public AustinTetra createAustinTetra() {
        return new AustinTetra();
    }

    /**
     * Create an instance of {@link RegistrationProfileStatus }
     * 
     */
    public RegistrationProfileStatus createRegistrationProfileStatus() {
        return new RegistrationProfileStatus();
    }

    /**
     * Create an instance of {@link EnablePaymentProvisioning }
     * 
     */
    public EnablePaymentProvisioning createEnablePaymentProvisioning() {
        return new EnablePaymentProvisioning();
    }

    /**
     * Create an instance of {@link InsuranceInformationList }
     * 
     */
    public InsuranceInformationList createInsuranceInformationList() {
        return new InsuranceInformationList();
    }

    /**
     * Create an instance of {@link PrimaryAddressList }
     * 
     */
    public PrimaryAddressList createPrimaryAddressList() {
        return new PrimaryAddressList();
    }

    /**
     * Create an instance of {@link SupplierSQId }
     * 
     */
    public SupplierSQId createSupplierSQId() {
        return new SupplierSQId();
    }

    /**
     * Create an instance of {@link LegalStructure }
     * 
     */
    public LegalStructure createLegalStructure() {
        return new LegalStructure();
    }

    /**
     * Create an instance of {@link TaxIdentificationType }
     * 
     */
    public TaxIdentificationType createTaxIdentificationType() {
        return new TaxIdentificationType();
    }

    /**
     * Create an instance of {@link SupplierRegCourt }
     * 
     */
    public SupplierRegCourt createSupplierRegCourt() {
        return new SupplierRegCourt();
    }

    /**
     * Create an instance of {@link SupplierRegNumber }
     * 
     */
    public SupplierRegNumber createSupplierRegNumber() {
        return new SupplierRegNumber();
    }

    /**
     * Create an instance of {@link VATExempt }
     * 
     */
    public VATExempt createVATExempt() {
        return new VATExempt();
    }

    /**
     * Create an instance of {@link ShoppingCommodityCode }
     * 
     */
    public ShoppingCommodityCode createShoppingCommodityCode() {
        return new ShoppingCommodityCode();
    }

    /**
     * Create an instance of {@link SupportedCurrencyList }
     * 
     */
    public SupportedCurrencyList createSupportedCurrencyList() {
        return new SupportedCurrencyList();
    }

    /**
     * Create an instance of {@link EnabledCurrencyList }
     * 
     */
    public EnabledCurrencyList createEnabledCurrencyList() {
        return new EnabledCurrencyList();
    }

    /**
     * Create an instance of {@link AddressList }
     * 
     */
    public AddressList createAddressList() {
        return new AddressList();
    }

    /**
     * Create an instance of {@link ContactList }
     * 
     */
    public ContactList createContactList() {
        return new ContactList();
    }

    /**
     * Create an instance of {@link DiversityClassificationList }
     * 
     */
    public DiversityClassificationList createDiversityClassificationList() {
        return new DiversityClassificationList();
    }

    /**
     * Create an instance of {@link ContactRef }
     * 
     */
    public ContactRef createContactRef() {
        return new ContactRef();
    }

    /**
     * Create an instance of {@link Percentage }
     * 
     */
    public Percentage createPercentage() {
        return new Percentage();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link MobilePhone }
     * 
     */
    public MobilePhone createMobilePhone() {
        return new MobilePhone();
    }

    /**
     * Create an instance of {@link SupplierResponseMessage }
     * 
     */
    public SupplierResponseMessage createSupplierResponseMessage() {
        return new SupplierResponseMessage();
    }

    /**
     * Create an instance of {@link DistributionMethod }
     * 
     */
    public DistributionMethod createDistributionMethod() {
        return new DistributionMethod();
    }

    /**
     * Create an instance of {@link SupplierSyncMessage }
     * 
     */
    public SupplierSyncMessage createSupplierSyncMessage() {
        return new SupplierSyncMessage();
    }

    /**
     * Create an instance of {@link LookupRequestMessage }
     * 
     */
    public LookupRequestMessage createLookupRequestMessage() {
        return new LookupRequestMessage();
    }

    /**
     * Create an instance of {@link SupplierNumber }
     * 
     */
    public SupplierNumber createSupplierNumber() {
        return new SupplierNumber();
    }

}
