-- Create table for ResourceDescription
CREATE TABLE KFS.CU_SYS_RSC_DESC_T (
    RSC_CD VARCHAR2(30) NOT NULL,
    RSC_DESC VARCHAR2(255) NOT NULL,
    ACTV_IND NUMBER(1) DEFAULT 1 NOT NULL,
    OBJ_ID VARCHAR2(36) NOT NULL,
    VER_NBR NUMBER(8) DEFAULT 1 NOT NULL,
    LAST_UPDT_TS TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CU_SYS_RSC_DESC_TP1 PRIMARY KEY (RSC_CD),
    CONSTRAINT CU_SYS_RSC_DESC_TC0 UNIQUE (OBJ_ID)
);

-- Create table for ResourceAuthenticator
CREATE TABLE KFS.CU_SYS_RSC_AUTH_T (
    AUTH_ID NUMBER(10) NOT NULL,
    AUTH_DESC VARCHAR2(255) NOT NULL,
    USR_NM_PWD VARCHAR2(255) NOT NULL,
    ACTV_IND NUMBER(1) DEFAULT 1 NOT NULL,
    OBJ_ID VARCHAR2(36) NOT NULL,
    VER_NBR NUMBER(8) DEFAULT 1 NOT NULL,
    LAST_UPDT_TS TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CU_SYS_RSC_AUTH_TP1 PRIMARY KEY (AUTH_ID),
    CONSTRAINT CU_SYS_RSC_AUTH_TC0 UNIQUE (OBJ_ID)
);

-- Create join table for ResourceAuthenticator to ResourceDescription relationship
CREATE TABLE KFS.CU_SYS_RSC_AUTH_DESC_T (
    AUTH_ID NUMBER(10) NOT NULL,
    RSC_CD VARCHAR2(30) NOT NULL,
    CONSTRAINT CU_SYS_RSC_AUTH_DESC_TP1 PRIMARY KEY (AUTH_ID, RSC_CD),
    CONSTRAINT CU_SYS_RSC_AUTH_DESC_TR1 FOREIGN KEY (AUTH_ID) REFERENCES KFS.CU_SYS_RSC_AUTH_T (AUTH_ID),
    CONSTRAINT CU_SYS_RSC_AUTH_DESC_TR2 FOREIGN KEY (RSC_CD) REFERENCES KFS.CU_SYS_RSC_DESC_T (RSC_CD)
);

-- Create sequence for ResourceAuthenticator ID
CREATE SEQUENCE KFS.CU_SYS_RSC_AUTH_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;
