package edu.cornell.kfs.cemi.module.cg.batch.legacy;

public enum NovelutionAwardCsvTableColumns {
    SPREADSHEET_KEY,
    ADD_ONLY,
    AWARD,
    AUTOCOMPLETE,
    AWARD_REFERENCE_ID,
    AWARD_NUMBER,
    SPONSOR_AWARD_REFERENCE_NUMBER,
    AWARD_NAME,
    AWARD_DESCRIPTION,
    AWARD_SIGNED_DATE,
    PURPOSE_CODE,
    INSTITUTIONAL_ID,
    AWARD_LIFECYCLE_STATUS,
    SUB_AWARD,
    ZERO_AMOUNT_AWARD,
    COST_SHARE_TOTAL_AMOUNT,
    AUTHORIZED_AMOUNT,
    ANTICIPATED_SPONSOR_DIRECT_COST_AMOUNT,
    ANTICIPATED_SPONSOR_FACILITIES_AND_ADMINISTRATION_AMOUNT,
    AWARD_SCHEDULE,
    FEDERAL_AWARD_ID_NUMBER,
    CFDA_NUMBER,
    LINE_CFDA_NUMBER
}
