vendor.employee.comparison.report.file.name=Vendor_Employee_Comparison_Results_
vendor.employee.comparison.report.title=Vendor Employee Comparison Report
vendor.employee.comparison.report.section.opening=****************************** {0} ****************************************
vendor.employee.comparison.report.section.closing=***************************************************************************
vendor.employee.comparison.report.summary.line={0}: {2}
vendor.employee.comparison.report.detail.summary={0} with {1}
vendor.employee.comparison.report.detail.item={0}: {1}
