package edu.cornell.kfs.cemi.vnd;

public interface CemiRemitToSupplierParameterConstants {
    
    public static final String COPY_CEMI_REMIT_TO_SUPPLIER_FILE_TO_OUTBOUND_FOLDER = "COPY_CEMI_REMIT_TO_SUPPLIER_FILE_TO_OUTBOUND_FOLDER";
    public static final String CEMI_REMIT_TO_SUPPLIER_EXTRACT_SUPPLIER_DATETIME = "CEMI_REMIT_TO_SUPPLIER_EXTRACT_SUPPLIER_DATETIME";
    public static final String CEMI_SUPPLIER_ORDER_FROM_EXTRACT_SUPPLIER_DATETIME = "CEMI_SUPPLIER_ORDER_FROM_EXTRACT_SUPPLIER_DATETIME";

}
