//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.14 at 02:38:16 PM EST 
//


package edu.cornell.kfs.concur.batch.xmlObjects.test;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Notification" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Context" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *                   &lt;element name="EventDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="EventType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="NotificationURI" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="ObjectType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="ObjectURI" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "notification"
})
@XmlRootElement(name = "NotificationList")
public class NotificationList {

    @XmlElement(name = "Notification", required = true)
    protected List<NotificationList.Notification> notification;

    /**
     * Gets the value of the notification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the notification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNotification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NotificationList.Notification }
     * 
     * 
     */
    public List<NotificationList.Notification> getNotification() {
        if (notification == null) {
            notification = new ArrayList<NotificationList.Notification>();
        }
        return this.notification;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Context" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
     *         &lt;element name="EventDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="EventType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="NotificationURI" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="ObjectType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="ObjectURI" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "context",
        "eventDateTime",
        "eventType",
        "notificationURI",
        "objectType",
        "objectURI"
    })
    public static class Notification {

        @XmlElement(name = "Context", required = true, nillable = true)
        protected Object context;
        @XmlElement(name = "EventDateTime", required = true)
        protected String eventDateTime;
        @XmlElement(name = "EventType", required = true)
        protected String eventType;
        @XmlElement(name = "NotificationURI", required = true)
        protected String notificationURI;
        @XmlElement(name = "ObjectType", required = true)
        protected String objectType;
        @XmlElement(name = "ObjectURI", required = true)
        protected String objectURI;

        /**
         * Gets the value of the context property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getContext() {
            return context;
        }

        /**
         * Sets the value of the context property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setContext(Object value) {
            this.context = value;
        }

        /**
         * Gets the value of the eventDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEventDateTime() {
            return eventDateTime;
        }

        /**
         * Sets the value of the eventDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEventDateTime(String value) {
            this.eventDateTime = value;
        }

        /**
         * Gets the value of the eventType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEventType() {
            return eventType;
        }

        /**
         * Sets the value of the eventType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEventType(String value) {
            this.eventType = value;
        }

        /**
         * Gets the value of the notificationURI property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNotificationURI() {
            return notificationURI;
        }

        /**
         * Sets the value of the notificationURI property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNotificationURI(String value) {
            this.notificationURI = value;
        }

        /**
         * Gets the value of the objectType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getObjectType() {
            return objectType;
        }

        /**
         * Sets the value of the objectType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setObjectType(String value) {
            this.objectType = value;
        }

        /**
         * Gets the value of the objectURI property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getObjectURI() {
            return objectURI;
        }

        /**
         * Sets the value of the objectURI property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setObjectURI(String value) {
            this.objectURI = value;
        }

    }

}
