//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.14 at 02:38:16 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.concursolutions.com/api/notification/2012/06", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.cornell.kfs.concur.batch.xmlObjects.test;
