package edu.cornell.kfs.pmw.batch;

public class PaymentWorksParameterConstants {
    public static final String PAYMENTWORKS_PARAMETER_NAMESPACE = "KFS-PMW";
    
    public static final String PAYMENTWORKS_NEW_VENDOR_REPORT_EMAIL_FROM_ADDRESS = "PAYMENTWORKS_NEW_VENDOR_REPORT_EMAIL_FROM_ADDRESS";
    public static final String PAYMENTWORKS_NEW_VENDOR_REPORT_EMAIL_TO_ADDRESS = "PAYMENTWORKS_NEW_VENDOR_REPORT_EMAIL_TO_ADDRESS";
    public static final String PAYMENTWORKS_NEW_VENDOR_REPORT_NO_PENDING_VENDORS_FOUND_EMAIL_BODY = "PAYMENTWORKS_NEW_VENDOR_REPORT_NO_PENDING_VENDORS_FOUND_EMAIL_BODY";
    public static final String PAYMENTWORKS_NEW_VENDOR_REPORT_NO_PENDING_VENDORS_FOUND_EMAIL_SUBJECT = "PAYMENTWORKS_NEW_VENDOR_REPORT_NO_PENDING_VENDORS_FOUND_EMAIL_SUBJECT";
    public static final String PAYMENTWORKS_NEW_VENDOR_REPORT_FILE_NAME_PREFIX = "PAYMENTWORKS_NEW_VENDOR_REPORT_FILE_NAME_PREFIX";
    public static final String PAYMENTWORKS_NEW_VENDOR_REPORT_TITLE = "PAYMENTWORKS_NEW_VENDOR_REPORT_TITLE";
    public static final String PAYMENTWORKS_NEW_VENDOR_REPORT_SUMMARY_SUB_TITLE = "PAYMENTWORKS_NEW_VENDOR_REPORT_SUMMARY_SUB_TITLE";
    public static final String PAYMENTWORKS_NEW_VENDOR_REPORT_PENDING_NEW_VENDORS_FOUND_LABEL = "PAYMENTWORKS_NEW_VENDOR_REPORT_PENDING_NEW_VENDORS_FOUND_LABEL";
    public static final String PAYMENTWORKS_NEW_VENDOR_REPORT_PENDING_NEW_VENDORS_NOT_PROCESSED_LABEL = "PAYMENTWORKS_NEW_VENDOR_REPORT_PENDING_NEW_VENDORS_NOT_PROCESSED_LABEL";
    public static final String PAYMENTWORKS_NEW_VENDOR_REPORT_PENDING_NEW_VENDORS_SUCCESSFULLY_PROCESSED_LABEL = "PAYMENTWORKS_NEW_VENDOR_REPORT_PENDING_NEW_VENDORS_SUCCESSFULLY_PROCESSED_LABEL";
    public static final String PAYMENTWORKS_NEW_VENDOR_REPORT_PENDING_NEW_VENDORS_ERRORED_LABEL = "PAYMENTWORKS_NEW_VENDOR_REPORT_PENDING_NEW_VENDORS_ERRORED_LABEL";
    public static final String PAYMENTWORKS_NEW_VENDOR_REPORT_VENDORS_PROCESSED_SUB_TITLE = "PAYMENTWORKS_NEW_VENDOR_REPORT_VENDORS_PROCESSED_SUB_TITLE";
    public static final String PAYMENTWORKS_NEW_VENDOR_REPORT_VENDORS_WITH_PROCESSING_ERRORS_SUB_TITLE = "PAYMENTWORKS_NEW_VENDOR_REPORT_VENDORS_WITH_PROCESSING_ERRORS_SUB_TITLE";
    public static final String PAYMENTWORKS_NEW_VENDOR_REPORT_UNPROCESSED_VENDORS_SUB_TITLE = "PAYMENTWORKS_NEW_VENDOR_REPORT_UNPROCESSED_VENDORS_SUB_TITLE";
    public static final String PAYMENTWORKS_NEW_VENDOR_REPORT_PAYMENTWORKS_VENDOR_ID_LABEL = "PAYMENTWORKS_NEW_VENDOR_REPORT_PAYMENTWORKS_VENDOR_ID_LABEL";
    public static final String PAYMENTWORKS_NEW_VENDOR_REPORT_DATE_SUBMITTED_LABEL = "PAYMENTWORKS_NEW_VENDOR_REPORT_DATE_SUBMITTED_LABEL";
    public static final String PAYMENTWORKS_NEW_VENDOR_REPORT_VENDOR_TYPE_LABEL = "PAYMENTWORKS_NEW_VENDOR_REPORT_VENDOR_TYPE_LABEL";
    public static final String PAYMENTWORKS_NEW_VENDOR_REPORT_VENDOR_NAME_LABEL = "PAYMENTWORKS_NEW_VENDOR_REPORT_VENDOR_NAME_LABEL";
    public static final String PAYMENTWORKS_NEW_VENDOR_REPORT_TAX_ID_TYPE_LABEL = "PAYMENTWORKS_NEW_VENDOR_REPORT_TAX_ID_TYPE_LABEL";
    public static final String PAYMENTWORKS_NEW_VENDOR_REPORT_SUBMITTER_EMAIL_ADDRESS_LABEL = "PAYMENTWORKS_NEW_VENDOR_REPORT_SUBMITTER_EMAIL_ADDRESS_LABEL";
    public static final String PAYMENTWORKS_NEW_VENDOR_REPORT_INITIATOR_NETID_LABEL = "PAYMENTWORKS_NEW_VENDOR_REPORT_INITIATOR_NETID_LABEL";
    public static final String PAYMENTWORKS_NEW_VENDOR_REPORT_ERRORS_LABEL = "PAYMENTWORKS_NEW_VENDOR_REPORT_ERRORS_LABEL";
}
