package edu.cornell.kfs.tax.dataaccess.impl;

/**
 * Helper enum for grouping various numeric statistics that are collected
 * during the transaction detail creation and processing.
 */
enum TaxStatType {
    NUM_TRANSACTION_ROWS("Total Number of Transaction Detail Rows"),
    NUM_NULL_TAX_NUMBERS("Tax Source Rows with Null Tax Numbers"),
    NUM_NULL_TAX_NUMBERS_FOR_DISTINCT_PAYEES("Payees with Null Tax Numbers"),
    NUM_NULL_DOCUMENT_HEADERS("Tax Source Rows with Null Document Headers"),
    NUM_NO_DOCUMENT_HEADERS("Tax Source Rows without Document Headers"),
    NUM_NO_ENTITY_NAME("Tax Source Rows without Initiator Names"),
    NUM_NO_ACCOUNT("Tax Source Rows without Valid Accounts"),
    NUM_NO_ORG("Tax Source Rows without Valid Orgs"),
    NUM_EXCLUDED_ASSIGNED_INCOME_CODES("Total Tax Source Rows with Excluded Income Codes"),
    NUM_EXCLUDED_ASSIGNED_INCOME_CODES_DV("DV Tax Source Rows with Excluded Income Codes"),
    NUM_EXCLUDED_ASSIGNED_INCOME_CODES_PDP("PDP Tax Source Rows with Excluded Income Codes"),
    NUM_EXCLUDED_ASSIGNED_INCOME_CODE_SUBTYPES("Total Tax Source Rows with Excluded Income Code SubTypes"),
    NUM_EXCLUDED_ASSIGNED_INCOME_CODE_SUBTYPES_DV("DV Tax Source Rows with Excluded Income Code SubTypes"),
    NUM_EXCLUDED_ASSIGNED_INCOME_CODE_SUBTYPES_PDP("PDP Tax Source Rows with Excluded Income Code SubTypes"),
    NUM_DETERMINED_FED_TAX_WITHHELD_INCOME_CODES("Total Tax Source Rows with Fed-Tax-Withheld Income Codes"),
    NUM_DETERMINED_FED_TAX_WITHHELD_INCOME_CODES_DV("DV Tax Source Rows with Fed-Tax-Withheld Income Codes"),
    NUM_DETERMINED_FED_TAX_WITHHELD_INCOME_CODES_PDP("PDP Tax Source Rows with Fed-Tax-Withheld Income Codes"),
    NUM_UNDETERMINED_FED_TAX_WITHHELD_INCOME_CODES("Tax Source Rows with Undetermined Fed-Tax-Withheld Types"),
    NUM_DETERMINED_STATE_INC_TAX_WITHHELD_INCOME_CODES("Total Tax Source Rows with State-Inc-Tax-Withheld Income Codes"),
    NUM_DETERMINED_STATE_INC_TAX_WITHHELD_INCOME_CODES_DV("DV Tax Source Rows with State-Inc-Tax-Withheld Income Codes"),
    NUM_DETERMINED_STATE_INC_TAX_WITHHELD_INCOME_CODES_PDP("PDP Tax Source Rows with State-Inc-Tax-Withheld Income Codes"),
    NUM_UNDETERMINED_STATE_INC_TAX_WITHHELD_INCOME_CODES("Tax Source Rows with Undetermined State-Inc-Tax-Withheld Types"),
    NUM_DV_CHECK_STUB_TEXTS_ALTERED("DV Check Stubs Altered for Transaction Rows"),
    NUM_DV_CHECK_STUB_TEXTS_NOT_ALTERED("DV Check Stubs Not Altered for Transaction Rows"),
    NUM_FOREIGN_DRAFTS_SELECTED("DV Foreign Draft Tax Source Rows Selected"),
    NUM_FOREIGN_DRAFTS_IGNORED("DV Foreign Draft Tax Source Rows Ignored"),
    NUM_WIRE_TRANSFERS_SELECTED("DV Wire Transfer Tax Source Rows Selected"),
    NUM_WIRE_TRANSFERS_IGNORED("DV Wire Transfer Tax Source Rows Ignored"),
    NUM_BIO_RECORDS_WRITTEN("1042S Biographic Records Created"),
    NUM_DETAIL_RECORDS_WRITTEN("1042S Detail Records Created"),
    NUM_TAB_RECORDS_WRITTEN("1099 Tab Records Created"),
    NUM_NO_VENDOR("Payees without Vendors"),
    NUM_NO_PARENT_VENDOR("Payees without Parent Vendors"),
    NUM_VENDOR_NAMES_PARSED("Payees with Vendor Names Successfully Parsed"),
    NUM_VENDOR_NAMES_NOT_PARSED("Payees with Vendor Names Unsuccessfully Parsed"),
    NUM_NO_VENDOR_ADDRESS("Payees without Vendor Addresses"),
    NUM_NO_VENDOR_ADDRESS_US("Payees without US Vendor Addresses"),
    NUM_NO_VENDOR_ADDRESS_FOREIGN("Payees without Foreign Vendor Addresses"),
    NUM_PDP_DOCTYPE_EXCLUSIONS_DETERMINED("Transaction Rows with PDP Document Type Exclusions"),
    NUM_PAYMENT_REASON_EXCLUSIONS_DETERMINED("Transaction Rows with Payment Reason Exclusions"),
    NUM_VENDOR_TYPE_EXCLUSIONS_DETERMINED("Transaction Rows with Vendor Type Exclusions"),
    NUM_OWNERSHIP_TYPE_EXCLUSIONS_DETERMINED("Transaction Rows with Vendor Ownership Type Exclusions"),
    NUM_DOC_NOTE_SETS_RETRIEVED("Transaction Rows with Document Notes"),
    NUM_DOC_NOTE_SETS_NOT_RETRIEVED("Transaction Rows without Document Notes"),
    NUM_ROYALTY_OBJ_DV_CHK_STUB_INCLUSIONS_DETERMINED("Transaction Rows with DV Check Stub Inclusions"),
    NUM_ROYALTY_OBJ_DV_CHK_STUB_EXCLUSIONS_DETERMINED("Transaction Rows with DV Check Stub Exclusions"),
    NUM_ROYALTY_OBJ_DV_CHK_STUB_NEITHER_DETERMINED("Transaction Rows without DV Check Stub Inclusions or Exclusions"),
    NUM_INCOME_CODE_EXCLUDED_GROSS_AMOUNTS("Gross Amount Transaction Rows with Income Code Exclusions"),
    NUM_INCOME_CODE_SUBTYPE_EXCLUDED_GROSS_AMOUNTS("Gross Amount Transaction Rows with Income Code SubType Exclusions"),
    NUM_INCOME_CODE_EXCLUDED_FTW_AMOUNTS("Fed-Tax-Withheld Amount Transaction Rows with Income Code Exclusions"),
    NUM_INCOME_CODE_SUBTYPE_EXCLUDED_FTW_AMOUNTS("Fed-Tax-Withheld Amount Transaction Rows with Income Code SubType Exclusions"),
    NUM_INCOME_CODE_EXCLUDED_SITW_AMOUNTS("State-Inc-Tax-Withheld Amount Transaction Rows with Income Code Exclusions"),
    NUM_INCOME_CODE_SUBTYPE_EXCLUDED_SITW_AMOUNTS("State-Inc-Tax-Withheld Amount Transaction Rows with Income Code SubType Exclusions"),
    NUM_NO_BOX_DETERMINED_ROWS("Transaction Rows with Undetermined Box Type"),
    NUM_BIO_LINES_WITH_TRUNCATED_US_ADDRESS("1042S Biographic Lines with Truncated US Addresses"),
    NUM_BIO_LINES_WITH_TRUNCATED_FOREIGN_ADDRESS("1042S Biographic Lines with Truncated Foreign Addresses"),
    NUM_BIO_LINES_WITHOUT_US_ADDRESS("1042S Biographic Lines without US Addresses"),
    NUM_BIO_LINES_WITHOUT_FOREIGN_ADDRESS("1042S Biographic Lines without Foreign Addresses"),
    NUM_BIO_LINES_WITHOUT_ANY_ADDRESS("1042S Biographic Lines without Any Addresses"),
    NUM_DETAIL_LINES_WITH_POSITIVE_FTW_AMOUNT("1042S Detail Lines with Positive Fed-Tax-Withheld Amounts"),
    NUM_DETAIL_LINES_WITH_POSITIVE_SITW_AMOUNT("1042S Detail Lines with Positive State-Inc-Tax-Withheld Amounts"),
    NUM_GROSS_AMOUNTS_DETERMINED("Total Transaction Rows with Gross Amounts"),
    NUM_GROSS_AMOUNTS_DETERMINED_DV("DV Transaction Rows with Gross Amounts"),
    NUM_GROSS_AMOUNTS_DETERMINED_PDP("PDP Transaction Rows with Gross Amounts"),
    NUM_FTW_AMOUNTS_DETERMINED("Total Transaction Rows with Fed-Tax-Withheld Amounts"),
    NUM_FTW_AMOUNTS_DETERMINED_DV("DV Transaction Rows with Fed-Tax-Withheld Amounts"),
    NUM_FTW_AMOUNTS_DETERMINED_PDP("PDP Transaction Rows with Fed-Tax-Withheld Amounts"),
    NUM_SITW_AMOUNTS_DETERMINED("Total Transaction Rows with State-Inc-Tax-Withheld Amounts"),
    NUM_SITW_AMOUNTS_DETERMINED_DV("DV Transaction Rows with State-Inc-Tax-Withheld Amounts"),
    NUM_SITW_AMOUNTS_DETERMINED_PDP("PDP Transaction Rows with State-Inc-Tax-Withheld Amounts"),
    NUM_PAYMENT_ADDRESS_EXCLUSIONS_DETERMINED("Total Transaction Rows with Payment Address Exclusions"),
    NUM_PAYMENT_ADDRESS_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Payment Address Exclusions"),
    NUM_PAYMENT_ADDRESS_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Payment Address Exclusions"),
    NUM_DOC_NOTES_EXCLUSIONS_DETERMINED("Total Transaction Rows with Document Note Exclusions"),
    NUM_DOC_NOTES_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Document Note Exclusions"),
    NUM_DOC_NOTES_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Document Note Exclusions"),
    NUM_ROYALTY_CHART_ACCOUNT_INCLUSIONS_DETERMINED("Total Transaction Rows with Object-Chart-Account Royalties Inclusions"),
    NUM_ROYALTY_CHART_ACCOUNT_INCLUSIONS_DETERMINED_DV("DV Transaction Rows with Object-Chart-Account Royalties Inclusions"),
    NUM_ROYALTY_CHART_ACCOUNT_INCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Object-Chart-Account Royalties Inclusions"),
    NUM_ROYALTY_CHART_ACCOUNT_EXCLUSIONS_DETERMINED("Total Transaction Rows with Object-Chart-Account Royalties Exclusions"),
    NUM_ROYALTY_CHART_ACCOUNT_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Object-Chart-Account Royalties Exclusions"),
    NUM_ROYALTY_CHART_ACCOUNT_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Object-Chart-Account Royalties Exclusions"),
    NUM_ROYALTY_CHART_ACCOUNT_NEITHER_DETERMINED("Total Transaction Rows without Object-Chart-Account Royalties Inclusions or Exclusions"),
    NUM_ROYALTY_CHART_ACCOUNT_NEITHER_DETERMINED_DV("DV Transaction Rows without Object-Chart-Account Royalties Inclusions or Exclusions"),
    NUM_ROYALTY_CHART_ACCOUNT_NEITHER_DETERMINED_PDP("PDP Transaction Rows without Object-Chart-Account Royalties Inclusions or Exclusions"),
    NUM_FTW_CHART_ACCOUNT_INCLUSIONS_DETERMINED("Total Transaction Rows with Object-Chart-Account FTW Inclusions"),
    NUM_FTW_CHART_ACCOUNT_INCLUSIONS_DETERMINED_DV("DV Transaction Rows with Object-Chart-Account FTW Inclusions"),
    NUM_FTW_CHART_ACCOUNT_INCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Object-Chart-Account FTW Inclusions"),
    NUM_FTW_CHART_ACCOUNT_EXCLUSIONS_DETERMINED("Total Transaction Rows with Object-Chart-Account FTW Exclusions"),
    NUM_FTW_CHART_ACCOUNT_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Object-Chart-Account FTW Exclusions"),
    NUM_FTW_CHART_ACCOUNT_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Object-Chart-Account FTW Exclusions"),
    NUM_FTW_CHART_ACCOUNT_NEITHER_DETERMINED("Total Transaction Rows without Object-Chart-Account FTW Inclusions or Exclusions"),
    NUM_FTW_CHART_ACCOUNT_NEITHER_DETERMINED_DV("DV Transaction Rows without Object-Chart-Account FTW Inclusions or Exclusions"),
    NUM_FTW_CHART_ACCOUNT_NEITHER_DETERMINED_PDP("PDP Transaction Rows without Object-Chart-Account FTW Inclusions or Exclusions"),
    NUM_SITW_CHART_ACCOUNT_INCLUSIONS_DETERMINED("Total Transaction Rows with Object-Chart-Account SITW Inclusions"),
    NUM_SITW_CHART_ACCOUNT_INCLUSIONS_DETERMINED_DV("DV Transaction Rows with Object-Chart-Account SITW Inclusions"),
    NUM_SITW_CHART_ACCOUNT_INCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Object-Chart-Account SITW Inclusions"),
    NUM_SITW_CHART_ACCOUNT_EXCLUSIONS_DETERMINED("Total Transaction Rows with Object-Chart-Account SITW Exclusions"),
    NUM_SITW_CHART_ACCOUNT_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Object-Chart-Account SITW Exclusions"),
    NUM_SITW_CHART_ACCOUNT_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Object-Chart-Account SITW Exclusions"),
    NUM_SITW_CHART_ACCOUNT_NEITHER_DETERMINED("Total Transaction Rows without Object-Chart-Account SITW Inclusions or Exclusions"),
    NUM_SITW_CHART_ACCOUNT_NEITHER_DETERMINED_DV("DV Transaction Rows without Object-Chart-Account SITW Inclusions or Exclusions"),
    NUM_SITW_CHART_ACCOUNT_NEITHER_DETERMINED_PDP("PDP Transaction Rows without Object-Chart-Account SITW Inclusions or Exclusions"),
    NUM_INITIATOR_NETID_EXCLUSIONS_DETERMINED("Total Transaction Rows with Initiator NetID Exclusions"),
    NUM_INITIATOR_NETID_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Initiator NetID Exclusions"),
    NUM_INITIATOR_NETID_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Initiator NetID Exclusions"),
    NUM_NON_EMPL_COMP_VENDOR_NAME_INCLUSIONS_DETERMINED("Total Transaction Rows with Vendor Name Non-Employee-Comp Inclusions"),
    NUM_NON_EMPL_COMP_VENDOR_NAME_INCLUSIONS_DETERMINED_DV("DV Transaction Rows with Vendor Name Non-Employee-Comp Inclusions"),
    NUM_NON_EMPL_COMP_VENDOR_NAME_INCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Vendor Name Non-Employee-Comp Inclusions"),
    NUM_NON_EMPL_COMP_VENDOR_NAME_EXCLUSIONS_DETERMINED("Total Transaction Rows with Vendor Name Non-Employee-Comp Exclusions"),
    NUM_NON_EMPL_COMP_VENDOR_NAME_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Vendor Name Non-Employee-Comp Exclusions"),
    NUM_NON_EMPL_COMP_VENDOR_NAME_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Vendor Name Non-Employee-Comp Exclusions"),
    NUM_NON_EMPL_COMP_VENDOR_NAME_NEITHER_DETERMINED("Total Transaction Rows without Vendor Name Non-Employee-Comp Inclusions or Exclusions"),
    NUM_NON_EMPL_COMP_VENDOR_NAME_NEITHER_DETERMINED_DV("DV Transaction Rows without Vendor Name Non-Employee-Comp Inclusions or Exclusions"),
    NUM_NON_EMPL_COMP_VENDOR_NAME_NEITHER_DETERMINED_PDP("PDP Transaction Rows without Vendor Name Non-Employee-Comp Inclusions or Exclusions"),
    NUM_NON_EMPL_COMP_PARENT_VENDOR_NAME_INCLUSIONS_DETERMINED("Total Transaction Rows with Parent Vendor Name Non-Employee-Comp Inclusions"),
    NUM_NON_EMPL_COMP_PARENT_VENDOR_NAME_INCLUSIONS_DETERMINED_DV("DV Transaction Rows with Parent Vendor Name Non-Employee-Comp Inclusions"),
    NUM_NON_EMPL_COMP_PARENT_VENDOR_NAME_INCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Parent Vendor Name Non-Employee-Comp Inclusions"),
    NUM_NON_EMPL_COMP_PARENT_VENDOR_NAME_EXCLUSIONS_DETERMINED("Total Transaction Rows with Parent Vendor Name Non-Employee-Comp Exclusions"),
    NUM_NON_EMPL_COMP_PARENT_VENDOR_NAME_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Parent Vendor Name Non-Employee-Comp Exclusions"),
    NUM_NON_EMPL_COMP_PARENT_VENDOR_NAME_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Parent Vendor Name Non-Employee-Comp Exclusions"),
    NUM_NON_EMPL_COMP_PARENT_VENDOR_NAME_NEITHER_DETERMINED("Total Transaction Rows without Parent Vendor Name Non-Employee-Comp Inclusions or Exclusions"),
    NUM_NON_EMPL_COMP_PARENT_VENDOR_NAME_NEITHER_DETERMINED_DV("DV Transaction Rows without Parent Vendor Name Non-Employee-Comp Inclusions or Exclusions"),
    NUM_NON_EMPL_COMP_PARENT_VENDOR_NAME_NEITHER_DETERMINED_PDP("PDP Transaction Rows without Parent Vendor Name Non-Employee-Comp Inclusions or Exclusions"),
    NUM_NON_EMPL_COMP_DOC_TITLE_INCLUSIONS_DETERMINED("Total Transaction Rows with Doc Title Non-Employee-Comp Inclusions"),
    NUM_NON_EMPL_COMP_DOC_TITLE_INCLUSIONS_DETERMINED_DV("DV Transaction Rows with Doc Title Non-Employee-Comp Inclusions"),
    NUM_NON_EMPL_COMP_DOC_TITLE_INCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Doc Title Non-Employee-Comp Inclusions"),
    NUM_NON_EMPL_COMP_DOC_TITLE_EXCLUSIONS_DETERMINED("Total Transaction Rows with Doc Title Non-Employee-Comp Exclusions"),
    NUM_NON_EMPL_COMP_DOC_TITLE_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Doc Title Non-Employee-Comp Exclusions"),
    NUM_NON_EMPL_COMP_DOC_TITLE_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Doc Title Non-Employee-Comp Exclusions"),
    NUM_NON_EMPL_COMP_DOC_TITLE_NEITHER_DETERMINED("Total Transaction Rows without Doc Title Non-Employee-Comp Inclusions or Exclusions"),
    NUM_NON_EMPL_COMP_DOC_TITLE_NEITHER_DETERMINED_DV("DV Transaction Rows without Doc Title Non-Employee-Comp Inclusions or Exclusions"),
    NUM_NON_EMPL_COMP_DOC_TITLE_NEITHER_DETERMINED_PDP("PDP Transaction Rows without Doc Title Non-Employee-Comp Inclusions or Exclusions"),
    NUM_BOX1_DV_CHK_STUB_INCLUSIONS_DETERMINED("Total Transaction Rows with Box 1 DV Check Stub Text Inclusions"),
    NUM_BOX1_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 1 DV Check Stub Text Inclusions"),
    NUM_BOX1_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 1 DV Check Stub Text Inclusions"),
    NUM_BOX1_DV_CHK_STUB_EXCLUSIONS_DETERMINED("Total Transaction Rows with Box 1 DV Check Stub Text Exclusions"),
    NUM_BOX1_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 1 DV Check Stub Text Exclusions"),
    NUM_BOX1_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 1 DV Check Stub Text Exclusions"),
    NUM_BOX1_DV_CHK_STUB_NEITHER_DETERMINED("Total Transaction Rows without Box 1 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX1_DV_CHK_STUB_NEITHER_DETERMINED_DV("DV Transaction Rows without Box 1 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX1_DV_CHK_STUB_NEITHER_DETERMINED_PDP("PDP Transaction Rows without Box 1 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX2_DV_CHK_STUB_INCLUSIONS_DETERMINED("Total Transaction Rows with Box 2 DV Check Stub Text Inclusions"),
    NUM_BOX2_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 2 DV Check Stub Text Inclusions"),
    NUM_BOX2_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 2 DV Check Stub Text Inclusions"),
    NUM_BOX2_DV_CHK_STUB_EXCLUSIONS_DETERMINED("Total Transaction Rows with Box 2 DV Check Stub Text Exclusions"),
    NUM_BOX2_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 2 DV Check Stub Text Exclusions"),
    NUM_BOX2_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 2 DV Check Stub Text Exclusions"),
    NUM_BOX2_DV_CHK_STUB_NEITHER_DETERMINED("Total Transaction Rows without Box 2 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX2_DV_CHK_STUB_NEITHER_DETERMINED_DV("DV Transaction Rows without Box 2 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX2_DV_CHK_STUB_NEITHER_DETERMINED_PDP("PDP Transaction Rows without Box 2 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX3_DV_CHK_STUB_INCLUSIONS_DETERMINED("Total Transaction Rows with Box 3 DV Check Stub Text Inclusions"),
    NUM_BOX3_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 3 DV Check Stub Text Inclusions"),
    NUM_BOX3_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 3 DV Check Stub Text Inclusions"),
    NUM_BOX3_DV_CHK_STUB_EXCLUSIONS_DETERMINED("Total Transaction Rows with Box 3 DV Check Stub Text Exclusions"),
    NUM_BOX3_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 3 DV Check Stub Text Exclusions"),
    NUM_BOX3_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 3 DV Check Stub Text Exclusions"),
    NUM_BOX3_DV_CHK_STUB_NEITHER_DETERMINED("Total Transaction Rows without Box 3 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX3_DV_CHK_STUB_NEITHER_DETERMINED_DV("DV Transaction Rows without Box 3 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX3_DV_CHK_STUB_NEITHER_DETERMINED_PDP("PDP Transaction Rows without Box 3 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX4_DV_CHK_STUB_INCLUSIONS_DETERMINED("Total Transaction Rows with Box 4 DV Check Stub Text Inclusions"),
    NUM_BOX4_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 4 DV Check Stub Text Inclusions"),
    NUM_BOX4_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 4 DV Check Stub Text Inclusions"),
    NUM_BOX4_DV_CHK_STUB_EXCLUSIONS_DETERMINED("Total Transaction Rows with Box 4 DV Check Stub Text Exclusions"),
    NUM_BOX4_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 4 DV Check Stub Text Exclusions"),
    NUM_BOX4_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 4 DV Check Stub Text Exclusions"),
    NUM_BOX4_DV_CHK_STUB_NEITHER_DETERMINED("Total Transaction Rows without Box 4 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX4_DV_CHK_STUB_NEITHER_DETERMINED_DV("DV Transaction Rows without Box 4 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX4_DV_CHK_STUB_NEITHER_DETERMINED_PDP("PDP Transaction Rows without Box 4 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX5_DV_CHK_STUB_INCLUSIONS_DETERMINED("Total Transaction Rows with Box 5 DV Check Stub Text Inclusions"),
    NUM_BOX5_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 5 DV Check Stub Text Inclusions"),
    NUM_BOX5_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 5 DV Check Stub Text Inclusions"),
    NUM_BOX5_DV_CHK_STUB_EXCLUSIONS_DETERMINED("Total Transaction Rows with Box 5 DV Check Stub Text Exclusions"),
    NUM_BOX5_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 5 DV Check Stub Text Exclusions"),
    NUM_BOX5_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 5 DV Check Stub Text Exclusions"),
    NUM_BOX5_DV_CHK_STUB_NEITHER_DETERMINED("Total Transaction Rows without Box 5 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX5_DV_CHK_STUB_NEITHER_DETERMINED_DV("DV Transaction Rows without Box 5 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX5_DV_CHK_STUB_NEITHER_DETERMINED_PDP("PDP Transaction Rows without Box 5 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX6_DV_CHK_STUB_INCLUSIONS_DETERMINED("Total Transaction Rows with Box 6 DV Check Stub Text Inclusions"),
    NUM_BOX6_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 6 DV Check Stub Text Inclusions"),
    NUM_BOX6_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 6 DV Check Stub Text Inclusions"),
    NUM_BOX6_DV_CHK_STUB_EXCLUSIONS_DETERMINED("Total Transaction Rows with Box 6 DV Check Stub Text Exclusions"),
    NUM_BOX6_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 6 DV Check Stub Text Exclusions"),
    NUM_BOX6_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 6 DV Check Stub Text Exclusions"),
    NUM_BOX6_DV_CHK_STUB_NEITHER_DETERMINED("Total Transaction Rows without Box 6 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX6_DV_CHK_STUB_NEITHER_DETERMINED_DV("DV Transaction Rows without Box 6 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX6_DV_CHK_STUB_NEITHER_DETERMINED_PDP("PDP Transaction Rows without Box 6 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX7_DV_CHK_STUB_INCLUSIONS_DETERMINED("Total Transaction Rows with Box 7 DV Check Stub Text Inclusions"),
    NUM_BOX7_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 7 DV Check Stub Text Inclusions"),
    NUM_BOX7_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 7 DV Check Stub Text Inclusions"),
    NUM_BOX7_DV_CHK_STUB_EXCLUSIONS_DETERMINED("Total Transaction Rows with Box 7 DV Check Stub Text Exclusions"),
    NUM_BOX7_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 7 DV Check Stub Text Exclusions"),
    NUM_BOX7_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 7 DV Check Stub Text Exclusions"),
    NUM_BOX7_DV_CHK_STUB_NEITHER_DETERMINED("Total Transaction Rows without Box 7 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX7_DV_CHK_STUB_NEITHER_DETERMINED_DV("DV Transaction Rows without Box 7 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX7_DV_CHK_STUB_NEITHER_DETERMINED_PDP("PDP Transaction Rows without Box 7 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX8_DV_CHK_STUB_INCLUSIONS_DETERMINED("Total Transaction Rows with Box 8 DV Check Stub Text Inclusions"),
    NUM_BOX8_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 8 DV Check Stub Text Inclusions"),
    NUM_BOX8_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 8 DV Check Stub Text Inclusions"),
    NUM_BOX8_DV_CHK_STUB_EXCLUSIONS_DETERMINED("Total Transaction Rows with Box 8 DV Check Stub Text Exclusions"),
    NUM_BOX8_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 8 DV Check Stub Text Exclusions"),
    NUM_BOX8_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 8 DV Check Stub Text Exclusions"),
    NUM_BOX8_DV_CHK_STUB_NEITHER_DETERMINED("Total Transaction Rows without Box 8 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX8_DV_CHK_STUB_NEITHER_DETERMINED_DV("DV Transaction Rows without Box 8 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX8_DV_CHK_STUB_NEITHER_DETERMINED_PDP("PDP Transaction Rows without Box 8 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX10_DV_CHK_STUB_INCLUSIONS_DETERMINED("Total Transaction Rows with Box 10 DV Check Stub Text Inclusions"),
    NUM_BOX10_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 10 DV Check Stub Text Inclusions"),
    NUM_BOX10_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 10 DV Check Stub Text Inclusions"),
    NUM_BOX10_DV_CHK_STUB_EXCLUSIONS_DETERMINED("Total Transaction Rows with Box 10 DV Check Stub Text Exclusions"),
    NUM_BOX10_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 10 DV Check Stub Text Exclusions"),
    NUM_BOX10_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 10 DV Check Stub Text Exclusions"),
    NUM_BOX10_DV_CHK_STUB_NEITHER_DETERMINED("Total Transaction Rows without Box 10 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX10_DV_CHK_STUB_NEITHER_DETERMINED_DV("DV Transaction Rows without Box 10 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX10_DV_CHK_STUB_NEITHER_DETERMINED_PDP("PDP Transaction Rows without Box 10 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX11_DV_CHK_STUB_INCLUSIONS_DETERMINED("Total Transaction Rows with Box 11 DV Check Stub Text Inclusions"),
    NUM_BOX11_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 11 DV Check Stub Text Inclusions"),
    NUM_BOX11_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 11 DV Check Stub Text Inclusions"),
    NUM_BOX11_DV_CHK_STUB_EXCLUSIONS_DETERMINED("Total Transaction Rows with Box 11 DV Check Stub Text Exclusions"),
    NUM_BOX11_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 11 DV Check Stub Text Exclusions"),
    NUM_BOX11_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 11 DV Check Stub Text Exclusions"),
    NUM_BOX11_DV_CHK_STUB_NEITHER_DETERMINED("Total Transaction Rows without Box 11 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX11_DV_CHK_STUB_NEITHER_DETERMINED_DV("DV Transaction Rows without Box 11 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX11_DV_CHK_STUB_NEITHER_DETERMINED_PDP("PDP Transaction Rows without Box 11 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX12_DV_CHK_STUB_INCLUSIONS_DETERMINED("Total Transaction Rows with Box 12 DV Check Stub Text Inclusions"),
    NUM_BOX12_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 12 DV Check Stub Text Inclusions"),
    NUM_BOX12_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 12 DV Check Stub Text Inclusions"),
    NUM_BOX12_DV_CHK_STUB_EXCLUSIONS_DETERMINED("Total Transaction Rows with Box 12 DV Check Stub Text Exclusions"),
    NUM_BOX12_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 12 DV Check Stub Text Exclusions"),
    NUM_BOX12_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 12 DV Check Stub Text Exclusions"),
    NUM_BOX12_DV_CHK_STUB_NEITHER_DETERMINED("Total Transaction Rows without Box 12 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX12_DV_CHK_STUB_NEITHER_DETERMINED_DV("DV Transaction Rows without Box 12 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX12_DV_CHK_STUB_NEITHER_DETERMINED_PDP("PDP Transaction Rows without Box 12 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX13_DV_CHK_STUB_INCLUSIONS_DETERMINED("Total Transaction Rows with Box 13 DV Check Stub Text Inclusions"),
    NUM_BOX13_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 13 DV Check Stub Text Inclusions"),
    NUM_BOX13_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 13 DV Check Stub Text Inclusions"),
    NUM_BOX13_DV_CHK_STUB_EXCLUSIONS_DETERMINED("Total Transaction Rows with Box 13 DV Check Stub Text Exclusions"),
    NUM_BOX13_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 13 DV Check Stub Text Exclusions"),
    NUM_BOX13_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 13 DV Check Stub Text Exclusions"),
    NUM_BOX13_DV_CHK_STUB_NEITHER_DETERMINED("Total Transaction Rows without Box 13 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX13_DV_CHK_STUB_NEITHER_DETERMINED_DV("DV Transaction Rows without Box 13 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX13_DV_CHK_STUB_NEITHER_DETERMINED_PDP("PDP Transaction Rows without Box 13 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX14_DV_CHK_STUB_INCLUSIONS_DETERMINED("Total Transaction Rows with Box 14 DV Check Stub Text Inclusions"),
    NUM_BOX14_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 14 DV Check Stub Text Inclusions"),
    NUM_BOX14_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 14 DV Check Stub Text Inclusions"),
    NUM_BOX14_DV_CHK_STUB_EXCLUSIONS_DETERMINED("Total Transaction Rows with Box 14 DV Check Stub Text Exclusions"),
    NUM_BOX14_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 14 DV Check Stub Text Exclusions"),
    NUM_BOX14_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 14 DV Check Stub Text Exclusions"),
    NUM_BOX14_DV_CHK_STUB_NEITHER_DETERMINED("Total Transaction Rows without Box 14 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX14_DV_CHK_STUB_NEITHER_DETERMINED_DV("DV Transaction Rows without Box 14 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX14_DV_CHK_STUB_NEITHER_DETERMINED_PDP("PDP Transaction Rows without Box 14 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX15A_DV_CHK_STUB_INCLUSIONS_DETERMINED("Total Transaction Rows with Box 15A DV Check Stub Text Inclusions"),
    NUM_BOX15A_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 15A DV Check Stub Text Inclusions"),
    NUM_BOX15A_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 15A DV Check Stub Text Inclusions"),
    NUM_BOX15A_DV_CHK_STUB_EXCLUSIONS_DETERMINED("Total Transaction Rows with Box 15A DV Check Stub Text Exclusions"),
    NUM_BOX15A_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 15A DV Check Stub Text Exclusions"),
    NUM_BOX15A_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 15A DV Check Stub Text Exclusions"),
    NUM_BOX15A_DV_CHK_STUB_NEITHER_DETERMINED("Total Transaction Rows without Box 15A DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX15A_DV_CHK_STUB_NEITHER_DETERMINED_DV("DV Transaction Rows without Box 15A DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX15A_DV_CHK_STUB_NEITHER_DETERMINED_PDP("PDP Transaction Rows without Box 15A DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX15B_DV_CHK_STUB_INCLUSIONS_DETERMINED("Total Transaction Rows with Box 15B DV Check Stub Text Inclusions"),
    NUM_BOX15B_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 15B DV Check Stub Text Inclusions"),
    NUM_BOX15B_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 15B DV Check Stub Text Inclusions"),
    NUM_BOX15B_DV_CHK_STUB_EXCLUSIONS_DETERMINED("Total Transaction Rows with Box 15B DV Check Stub Text Exclusions"),
    NUM_BOX15B_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 15B DV Check Stub Text Exclusions"),
    NUM_BOX15B_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 15B DV Check Stub Text Exclusions"),
    NUM_BOX15B_DV_CHK_STUB_NEITHER_DETERMINED("Total Transaction Rows without Box 15B DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX15B_DV_CHK_STUB_NEITHER_DETERMINED_DV("DV Transaction Rows without Box 15B DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX15B_DV_CHK_STUB_NEITHER_DETERMINED_PDP("PDP Transaction Rows without Box 15B DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX16_DV_CHK_STUB_INCLUSIONS_DETERMINED("Total Transaction Rows with Box 16 DV Check Stub Text Inclusions"),
    NUM_BOX16_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 16 DV Check Stub Text Inclusions"),
    NUM_BOX16_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 16 DV Check Stub Text Inclusions"),
    NUM_BOX16_DV_CHK_STUB_EXCLUSIONS_DETERMINED("Total Transaction Rows with Box 16 DV Check Stub Text Exclusions"),
    NUM_BOX16_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 16 DV Check Stub Text Exclusions"),
    NUM_BOX16_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 16 DV Check Stub Text Exclusions"),
    NUM_BOX16_DV_CHK_STUB_NEITHER_DETERMINED("Total Transaction Rows without Box 16 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX16_DV_CHK_STUB_NEITHER_DETERMINED_DV("DV Transaction Rows without Box 16 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX16_DV_CHK_STUB_NEITHER_DETERMINED_PDP("PDP Transaction Rows without Box 16 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX18_DV_CHK_STUB_INCLUSIONS_DETERMINED("Total Transaction Rows with Box 18 DV Check Stub Text Inclusions"),
    NUM_BOX18_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 18 DV Check Stub Text Inclusions"),
    NUM_BOX18_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 18 DV Check Stub Text Inclusions"),
    NUM_BOX18_DV_CHK_STUB_EXCLUSIONS_DETERMINED("Total Transaction Rows with Box 18 DV Check Stub Text Exclusions"),
    NUM_BOX18_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("DV Transaction Rows with Box 18 DV Check Stub Text Exclusions"),
    NUM_BOX18_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("PDP Transaction Rows with Box 18 DV Check Stub Text Exclusions"),
    NUM_BOX18_DV_CHK_STUB_NEITHER_DETERMINED("Total Transaction Rows without Box 18 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX18_DV_CHK_STUB_NEITHER_DETERMINED_DV("DV Transaction Rows without Box 18 DV Check Stub Text Inclusions or Exclusions"),
    NUM_BOX18_DV_CHK_STUB_NEITHER_DETERMINED_PDP("PDP Transaction Rows without Box 18 DV Check Stub Text Inclusions or Exclusions");

    private final String statName;

    private TaxStatType(String statName) {
        this.statName = statName;
    }

    @Override
    public String toString() {
        return statName;
    }
}