package edu.cornell.kfs.tax.dataaccess.impl;

/**
 * Helper enum for grouping various numeric statistics that are collected
 * during the transaction detail creation and processing.
 */
public enum TaxStatType {
    NUM_TRANSACTION_ROWS("message.tax.num.transaction.rows"),
    NUM_NULL_TAX_NUMBERS("message.tax.num.null.tax.numbers"),
    NUM_NULL_TAX_NUMBERS_FOR_DISTINCT_PAYEES("message.tax.num.null.tax.numbers.for.distinct.payees"),
    NUM_NULL_DOCUMENT_HEADERS("message.tax.num.null.document.headers"),
    NUM_NO_DOCUMENT_HEADERS("message.tax.num.no.document.headers"),
    NUM_NO_ENTITY_NAME("message.tax.num.no.entity.name"),
    NUM_NO_ACCOUNT("message.tax.num.no.account"),
    NUM_NO_ORG("message.tax.num.no.org"),
    NUM_EXCLUDED_ASSIGNED_INCOME_CODES("message.tax.num.excluded.assigned.income.codes", true),
    NUM_EXCLUDED_ASSIGNED_INCOME_CODES_DV("message.tax.num.excluded.assigned.income.codes.dv"),
    NUM_EXCLUDED_ASSIGNED_INCOME_CODES_PDP("message.tax.num.excluded.assigned.income.codes.pdp"),
    NUM_EXCLUDED_ASSIGNED_INCOME_CODES_PRNC("message.tax.num.excluded.assigned.income.codes.prnc"),
    NUM_EXCLUDED_ASSIGNED_INCOME_CODE_SUBTYPES("message.tax.num.excluded.assigned.income.code.subtypes", true),
    NUM_EXCLUDED_ASSIGNED_INCOME_CODE_SUBTYPES_DV("message.tax.num.excluded.assigned.income.code.subtypes.dv"),
    NUM_EXCLUDED_ASSIGNED_INCOME_CODE_SUBTYPES_PDP("message.tax.num.excluded.assigned.income.code.subtypes.pdp"),
    NUM_EXCLUDED_ASSIGNED_INCOME_CODE_SUBTYPES_PRNC("message.tax.num.excluded.assigned.income.code.subtypes.prnc"),
    NUM_DETERMINED_FED_TAX_WITHHELD_INCOME_CODES("message.tax.num.determined.fed.tax.withheld.income.codes", true),
    NUM_DETERMINED_FED_TAX_WITHHELD_INCOME_CODES_DV("message.tax.num.determined.fed.tax.withheld.income.codes.dv"),
    NUM_DETERMINED_FED_TAX_WITHHELD_INCOME_CODES_PDP("message.tax.num.determined.fed.tax.withheld.income.codes.pdp"),
    NUM_DETERMINED_FED_TAX_WITHHELD_INCOME_CODES_PRNC("message.tax.num.determined.fed.tax.withheld.income.codes.prnc"),
    NUM_UNDETERMINED_FED_TAX_WITHHELD_INCOME_CODES("message.tax.num.undetermined.fed.tax.withheld.income.codes"),
    NUM_DETERMINED_STATE_INC_TAX_WITHHELD_INCOME_CODES("message.tax.num.determined.state.inc.tax.withheld.income.codes", true),
    NUM_DETERMINED_STATE_INC_TAX_WITHHELD_INCOME_CODES_DV("message.tax.num.determined.state.inc.tax.withheld.income.codes.dv"),
    NUM_DETERMINED_STATE_INC_TAX_WITHHELD_INCOME_CODES_PDP("message.tax.num.determined.state.inc.tax.withheld.income.codes.pdp"),
    NUM_DETERMINED_STATE_INC_TAX_WITHHELD_INCOME_CODES_PRNC("message.tax.num.determined.state.inc.tax.withheld.income.codes.prnc"),
    NUM_UNDETERMINED_STATE_INC_TAX_WITHHELD_INCOME_CODES("message.tax.num.undetermined.state.inc.tax.withheld.income.codes"),
    NUM_DV_CHECK_STUB_TEXTS_ALTERED("message.tax.num.dv.check.stub.texts.altered"),
    NUM_DV_CHECK_STUB_TEXTS_NOT_ALTERED("message.tax.num.dv.check.stub.texts.not.altered"),
    NUM_DV_FOREIGN_DRAFTS_SELECTED("message.tax.num.dv.foreign.drafts.selected"),
    NUM_DV_FOREIGN_DRAFTS_IGNORED("message.tax.num.dv.foreign.drafts.ignored"),
    NUM_DV_WIRE_TRANSFERS_SELECTED("message.tax.num.dv.wire.transfers.selected"),
    NUM_DV_WIRE_TRANSFERS_IGNORED("message.tax.num.dv.wire.transfers.ignored"),
    NUM_PRNC_FOREIGN_DRAFTS_SELECTED("message.tax.num.prnc.foreign.drafts.selected"),
    NUM_PRNC_FOREIGN_DRAFTS_IGNORED("message.tax.num.prnc.foreign.drafts.ignored"),
    NUM_PRNC_WIRE_TRANSFERS_SELECTED("message.tax.num.prnc.wire.transfers.selected"),
    NUM_PRNC_WIRE_TRANSFERS_IGNORED("message.tax.num.prnc.wire.transfers.ignored"),
    NUM_BIO_RECORDS_WRITTEN("message.tax.num.bio.records.written"),
    NUM_DETAIL_RECORDS_WRITTEN("message.tax.num.detail.records.written"),
    NUM_MISC_TAB_RECORDS_WRITTEN("message.tax.num.misc.tab.records.written"),
    NUM_NEC_TAB_RECORDS_WRITTEN("message.tax.num.nec.tab.records.written"),
    NUM_NO_VENDOR("message.tax.num.no.vendor"),
    NUM_NO_PARENT_VENDOR("message.tax.num.no.parent.vendor"),
    NUM_VENDOR_NAMES_PARSED("message.tax.num.vendor.names.parsed"),
    NUM_VENDOR_NAMES_NOT_PARSED("message.tax.num.vendor.names.not.parsed"),
    NUM_NO_VENDOR_ADDRESS("message.tax.num.no.vendor.address"),
    NUM_NO_VENDOR_ADDRESS_US("message.tax.num.no.vendor.address.us"),
    NUM_NO_VENDOR_ADDRESS_FOREIGN("message.tax.num.no.vendor.address.foreign"),
    NUM_PDP_DOCTYPE_EXCLUSIONS_DETERMINED("message.tax.num.pdp.doctype.exclusions.determined"),
    NUM_PAYMENT_REASON_EXCLUSIONS_DETERMINED("message.tax.num.payment.reason.exclusions.determined"),
    NUM_VENDOR_TYPE_EXCLUSIONS_DETERMINED("message.tax.num.vendor.type.exclusions.determined"),
    NUM_OWNERSHIP_TYPE_EXCLUSIONS_DETERMINED("message.tax.num.ownership.type.exclusions.determined"),
    NUM_DOC_NOTE_SETS_RETRIEVED("message.tax.num.doc.note.sets.retrieved"),
    NUM_DOC_NOTE_SETS_NOT_RETRIEVED("message.tax.num.doc.note.sets.not.retrieved"),
    NUM_ROYALTY_OBJ_DV_CHK_STUB_INCLUSIONS_DETERMINED("message.tax.num.royalty.obj.dv.chk.stub.inclusions.determined"),
    NUM_ROYALTY_OBJ_DV_CHK_STUB_EXCLUSIONS_DETERMINED("message.tax.num.royalty.obj.dv.chk.stub.exclusions.determined"),
    NUM_ROYALTY_OBJ_DV_CHK_STUB_NEITHER_DETERMINED("message.tax.num.royalty.obj.dv.chk.stub.neither.determined"),
    NUM_INCOME_CODE_EXCLUDED_GROSS_AMOUNTS("message.tax.num.income.code.excluded.gross.amounts"),
    NUM_INCOME_CODE_SUBTYPE_EXCLUDED_GROSS_AMOUNTS("message.tax.num.income.code.subtype.excluded.gross.amounts"),
    NUM_INCOME_CODE_EXCLUDED_FTW_AMOUNTS("message.tax.num.income.code.excluded.ftw.amounts"),
    NUM_INCOME_CODE_SUBTYPE_EXCLUDED_FTW_AMOUNTS("message.tax.num.income.code.subtype.excluded.ftw.amounts"),
    NUM_INCOME_CODE_EXCLUDED_SITW_AMOUNTS("message.tax.num.income.code.excluded.sitw.amounts"),
    NUM_INCOME_CODE_SUBTYPE_EXCLUDED_SITW_AMOUNTS("message.tax.num.income.code.subtype.excluded.sitw.amounts"),
    NUM_NO_BOX_DETERMINED_ROWS("message.tax.num.no.box.determined.rows"),
    NUM_BIO_LINES_WITH_TRUNCATED_US_ADDRESS("message.tax.num.bio.lines.with.truncated.us.address"),
    NUM_BIO_LINES_WITH_TRUNCATED_FOREIGN_ADDRESS("message.tax.num.bio.lines.with.truncated.foreign.address"),
    NUM_BIO_LINES_WITHOUT_US_ADDRESS("message.tax.num.bio.lines.without.us.address"),
    NUM_BIO_LINES_WITHOUT_FOREIGN_ADDRESS("message.tax.num.bio.lines.without.foreign.address"),
    NUM_BIO_LINES_WITHOUT_ANY_ADDRESS("message.tax.num.bio.lines.without.any.address"),
    NUM_DETAIL_LINES_WITH_POSITIVE_FTW_AMOUNT("message.tax.num.detail.lines.with.positive.ftw.amount"),
    NUM_DETAIL_LINES_WITH_POSITIVE_SITW_AMOUNT("message.tax.num.detail.lines.with.positive.sitw.amount"),
    NUM_GROSS_AMOUNTS_DETERMINED("message.tax.num.gross.amounts.determined", true),
    NUM_GROSS_AMOUNTS_DETERMINED_DV("message.tax.num.gross.amounts.determined.dv"),
    NUM_GROSS_AMOUNTS_DETERMINED_PDP("message.tax.num.gross.amounts.determined.pdp"),
    NUM_FTW_AMOUNTS_DETERMINED("message.tax.num.ftw.amounts.determined", true),
    NUM_FTW_AMOUNTS_DETERMINED_DV("message.tax.num.ftw.amounts.determined.dv"),
    NUM_FTW_AMOUNTS_DETERMINED_PDP("message.tax.num.ftw.amounts.determined.pdp"),
    NUM_SITW_AMOUNTS_DETERMINED("message.tax.num.sitw.amounts.determined", true),
    NUM_SITW_AMOUNTS_DETERMINED_DV("message.tax.num.sitw.amounts.determined.dv"),
    NUM_SITW_AMOUNTS_DETERMINED_PDP("message.tax.num.sitw.amounts.determined.pdp"),
    NUM_PAYMENT_ADDRESS_EXCLUSIONS_DETERMINED("message.tax.num.payment.address.exclusions.determined", true),
    NUM_PAYMENT_ADDRESS_EXCLUSIONS_DETERMINED_DV("message.tax.num.payment.address.exclusions.determined.dv"),
    NUM_PAYMENT_ADDRESS_EXCLUSIONS_DETERMINED_PDP("message.tax.num.payment.address.exclusions.determined.pdp"),
    NUM_DOC_NOTES_EXCLUSIONS_DETERMINED("message.tax.num.doc.notes.exclusions.determined", true),
    NUM_DOC_NOTES_EXCLUSIONS_DETERMINED_DV("message.tax.num.doc.notes.exclusions.determined.dv"),
    NUM_DOC_NOTES_EXCLUSIONS_DETERMINED_PDP("message.tax.num.doc.notes.exclusions.determined.pdp"),
    NUM_ROYALTY_CHART_ACCOUNT_INCLUSIONS_DETERMINED("message.tax.num.royalty.chart.account.inclusions.determined", true),
    NUM_ROYALTY_CHART_ACCOUNT_INCLUSIONS_DETERMINED_DV("message.tax.num.royalty.chart.account.inclusions.determined.dv"),
    NUM_ROYALTY_CHART_ACCOUNT_INCLUSIONS_DETERMINED_PDP("message.tax.num.royalty.chart.account.inclusions.determined.pdp"),
    NUM_ROYALTY_CHART_ACCOUNT_EXCLUSIONS_DETERMINED("message.tax.num.royalty.chart.account.exclusions.determined", true),
    NUM_ROYALTY_CHART_ACCOUNT_EXCLUSIONS_DETERMINED_DV("message.tax.num.royalty.chart.account.exclusions.determined.dv"),
    NUM_ROYALTY_CHART_ACCOUNT_EXCLUSIONS_DETERMINED_PDP("message.tax.num.royalty.chart.account.exclusions.determined.pdp"),
    NUM_ROYALTY_CHART_ACCOUNT_NEITHER_DETERMINED("message.tax.num.royalty.chart.account.neither.determined", true),
    NUM_ROYALTY_CHART_ACCOUNT_NEITHER_DETERMINED_DV("message.tax.num.royalty.chart.account.neither.determined.dv"),
    NUM_ROYALTY_CHART_ACCOUNT_NEITHER_DETERMINED_PDP("message.tax.num.royalty.chart.account.neither.determined.pdp"),
    NUM_FTW_CHART_ACCOUNT_INCLUSIONS_DETERMINED("message.tax.num.ftw.chart.account.inclusions.determined", true),
    NUM_FTW_CHART_ACCOUNT_INCLUSIONS_DETERMINED_DV("message.tax.num.ftw.chart.account.inclusions.determined.dv"),
    NUM_FTW_CHART_ACCOUNT_INCLUSIONS_DETERMINED_PDP("message.tax.num.ftw.chart.account.inclusions.determined.pdp"),
    NUM_FTW_CHART_ACCOUNT_EXCLUSIONS_DETERMINED("message.tax.num.ftw.chart.account.exclusions.determined", true),
    NUM_FTW_CHART_ACCOUNT_EXCLUSIONS_DETERMINED_DV("message.tax.num.ftw.chart.account.exclusions.determined.dv"),
    NUM_FTW_CHART_ACCOUNT_EXCLUSIONS_DETERMINED_PDP("message.tax.num.ftw.chart.account.exclusions.determined.pdp"),
    NUM_FTW_CHART_ACCOUNT_NEITHER_DETERMINED("message.tax.num.ftw.chart.account.neither.determined", true),
    NUM_FTW_CHART_ACCOUNT_NEITHER_DETERMINED_DV("message.tax.num.ftw.chart.account.neither.determined.dv"),
    NUM_FTW_CHART_ACCOUNT_NEITHER_DETERMINED_PDP("message.tax.num.ftw.chart.account.neither.determined.pdp"),
    NUM_SITW_CHART_ACCOUNT_INCLUSIONS_DETERMINED("message.tax.num.sitw.chart.account.inclusions.determined", true),
    NUM_SITW_CHART_ACCOUNT_INCLUSIONS_DETERMINED_DV("message.tax.num.sitw.chart.account.inclusions.determined.dv"),
    NUM_SITW_CHART_ACCOUNT_INCLUSIONS_DETERMINED_PDP("message.tax.num.sitw.chart.account.inclusions.determined.pdp"),
    NUM_SITW_CHART_ACCOUNT_EXCLUSIONS_DETERMINED("message.tax.num.sitw.chart.account.exclusions.determined", true),
    NUM_SITW_CHART_ACCOUNT_EXCLUSIONS_DETERMINED_DV("message.tax.num.sitw.chart.account.exclusions.determined.dv"),
    NUM_SITW_CHART_ACCOUNT_EXCLUSIONS_DETERMINED_PDP("message.tax.num.sitw.chart.account.exclusions.determined.pdp"),
    NUM_SITW_CHART_ACCOUNT_NEITHER_DETERMINED("message.tax.num.sitw.chart.account.neither.determined", true),
    NUM_SITW_CHART_ACCOUNT_NEITHER_DETERMINED_DV("message.tax.num.sitw.chart.account.neither.determined.dv"),
    NUM_SITW_CHART_ACCOUNT_NEITHER_DETERMINED_PDP("message.tax.num.sitw.chart.account.neither.determined.pdp"),
    NUM_INITIATOR_NETID_EXCLUSIONS_DETERMINED("message.tax.num.initiator.netid.exclusions.determined", true),
    NUM_INITIATOR_NETID_EXCLUSIONS_DETERMINED_DV("message.tax.num.initiator.netid.exclusions.determined.dv"),
    NUM_INITIATOR_NETID_EXCLUSIONS_DETERMINED_PDP("message.tax.num.initiator.netid.exclusions.determined.pdp"),
    NUM_NON_EMPL_COMP_VENDOR_NAME_INCLUSIONS_DETERMINED("message.tax.num.non.empl.comp.vendor.name.inclusions.determined", true),
    NUM_NON_EMPL_COMP_VENDOR_NAME_INCLUSIONS_DETERMINED_DV("message.tax.num.non.empl.comp.vendor.name.inclusions.determined.dv"),
    NUM_NON_EMPL_COMP_VENDOR_NAME_INCLUSIONS_DETERMINED_PDP("message.tax.num.non.empl.comp.vendor.name.inclusions.determined.pdp"),
    NUM_NON_EMPL_COMP_VENDOR_NAME_EXCLUSIONS_DETERMINED("message.tax.num.non.empl.comp.vendor.name.exclusions.determined", true),
    NUM_NON_EMPL_COMP_VENDOR_NAME_EXCLUSIONS_DETERMINED_DV("message.tax.num.non.empl.comp.vendor.name.exclusions.determined.dv"),
    NUM_NON_EMPL_COMP_VENDOR_NAME_EXCLUSIONS_DETERMINED_PDP("message.tax.num.non.empl.comp.vendor.name.exclusions.determined.pdp"),
    NUM_NON_EMPL_COMP_VENDOR_NAME_NEITHER_DETERMINED("message.tax.num.non.empl.comp.vendor.name.neither.determined", true),
    NUM_NON_EMPL_COMP_VENDOR_NAME_NEITHER_DETERMINED_DV("message.tax.num.non.empl.comp.vendor.name.neither.determined.dv"),
    NUM_NON_EMPL_COMP_VENDOR_NAME_NEITHER_DETERMINED_PDP("message.tax.num.non.empl.comp.vendor.name.neither.determined.pdp"),
    NUM_NON_EMPL_COMP_PARENT_VENDOR_NAME_INCLUSIONS_DETERMINED("message.tax.num.non.empl.comp.parent.vendor.name.inclusions.determined", true),
    NUM_NON_EMPL_COMP_PARENT_VENDOR_NAME_INCLUSIONS_DETERMINED_DV("message.tax.num.non.empl.comp.parent.vendor.name.inclusions.determined.dv"),
    NUM_NON_EMPL_COMP_PARENT_VENDOR_NAME_INCLUSIONS_DETERMINED_PDP("message.tax.num.non.empl.comp.parent.vendor.name.inclusions.determined.pdp"),
    NUM_NON_EMPL_COMP_PARENT_VENDOR_NAME_EXCLUSIONS_DETERMINED("message.tax.num.non.empl.comp.parent.vendor.name.exclusions.determined", true),
    NUM_NON_EMPL_COMP_PARENT_VENDOR_NAME_EXCLUSIONS_DETERMINED_DV("message.tax.num.non.empl.comp.parent.vendor.name.exclusions.determined.dv"),
    NUM_NON_EMPL_COMP_PARENT_VENDOR_NAME_EXCLUSIONS_DETERMINED_PDP("message.tax.num.non.empl.comp.parent.vendor.name.exclusions.determined.pdp"),
    NUM_NON_EMPL_COMP_PARENT_VENDOR_NAME_NEITHER_DETERMINED("message.tax.num.non.empl.comp.parent.vendor.name.neither.determined", true),
    NUM_NON_EMPL_COMP_PARENT_VENDOR_NAME_NEITHER_DETERMINED_DV("message.tax.num.non.empl.comp.parent.vendor.name.neither.determined.dv"),
    NUM_NON_EMPL_COMP_PARENT_VENDOR_NAME_NEITHER_DETERMINED_PDP("message.tax.num.non.empl.comp.parent.vendor.name.neither.determined.pdp"),
    NUM_NON_EMPL_COMP_DOC_TITLE_INCLUSIONS_DETERMINED("message.tax.num.non.empl.comp.doc.title.inclusions.determined", true),
    NUM_NON_EMPL_COMP_DOC_TITLE_INCLUSIONS_DETERMINED_DV("message.tax.num.non.empl.comp.doc.title.inclusions.determined.dv"),
    NUM_NON_EMPL_COMP_DOC_TITLE_INCLUSIONS_DETERMINED_PDP("message.tax.num.non.empl.comp.doc.title.inclusions.determined.pdp"),
    NUM_NON_EMPL_COMP_DOC_TITLE_EXCLUSIONS_DETERMINED("message.tax.num.non.empl.comp.doc.title.exclusions.determined", true),
    NUM_NON_EMPL_COMP_DOC_TITLE_EXCLUSIONS_DETERMINED_DV("message.tax.num.non.empl.comp.doc.title.exclusions.determined.dv"),
    NUM_NON_EMPL_COMP_DOC_TITLE_EXCLUSIONS_DETERMINED_PDP("message.tax.num.non.empl.comp.doc.title.exclusions.determined.pdp"),
    NUM_NON_EMPL_COMP_DOC_TITLE_NEITHER_DETERMINED("message.tax.num.non.empl.comp.doc.title.neither.determined", true),
    NUM_NON_EMPL_COMP_DOC_TITLE_NEITHER_DETERMINED_DV("message.tax.num.non.empl.comp.doc.title.neither.determined.dv"),
    NUM_NON_EMPL_COMP_DOC_TITLE_NEITHER_DETERMINED_PDP("message.tax.num.non.empl.comp.doc.title.neither.determined.pdp"),
    NUM_MISCRENTS_DV_CHK_STUB_INCLUSIONS_DETERMINED("message.tax.num.miscrents.dv.chk.stub.inclusions.determined", true),
    NUM_MISCRENTS_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("message.tax.num.miscrents.dv.chk.stub.inclusions.determined.dv"),
    NUM_MISCRENTS_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("message.tax.num.miscrents.dv.chk.stub.inclusions.determined.pdp"),
    NUM_MISCRENTS_DV_CHK_STUB_EXCLUSIONS_DETERMINED("message.tax.num.miscrents.dv.chk.stub.exclusions.determined", true),
    NUM_MISCRENTS_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("message.tax.num.miscrents.dv.chk.stub.exclusions.determined.dv"),
    NUM_MISCRENTS_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("message.tax.num.miscrents.dv.chk.stub.exclusions.determined.pdp"),
    NUM_MISCRENTS_DV_CHK_STUB_NEITHER_DETERMINED("message.tax.num.miscrents.dv.chk.stub.neither.determined", true),
    NUM_MISCRENTS_DV_CHK_STUB_NEITHER_DETERMINED_DV("message.tax.num.miscrents.dv.chk.stub.neither.determined.dv"),
    NUM_MISCRENTS_DV_CHK_STUB_NEITHER_DETERMINED_PDP("message.tax.num.miscrents.dv.chk.stub.neither.determined.pdp"),
    NUM_MISCROYALTIES_DV_CHK_STUB_INCLUSIONS_DETERMINED("message.tax.num.miscroyalties.dv.chk.stub.inclusions.determined", true),
    NUM_MISCROYALTIES_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("message.tax.num.miscroyalties.dv.chk.stub.inclusions.determined.dv"),
    NUM_MISCROYALTIES_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("message.tax.num.miscroyalties.dv.chk.stub.inclusions.determined.pdp"),
    NUM_MISCROYALTIES_DV_CHK_STUB_EXCLUSIONS_DETERMINED("message.tax.num.miscroyalties.dv.chk.stub.exclusions.determined", true),
    NUM_MISCROYALTIES_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("message.tax.num.miscroyalties.dv.chk.stub.exclusions.determined.dv"),
    NUM_MISCROYALTIES_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("message.tax.num.miscroyalties.dv.chk.stub.exclusions.determined.pdp"),
    NUM_MISCROYALTIES_DV_CHK_STUB_NEITHER_DETERMINED("message.tax.num.miscroyalties.dv.chk.stub.neither.determined", true),
    NUM_MISCROYALTIES_DV_CHK_STUB_NEITHER_DETERMINED_DV("message.tax.num.miscroyalties.dv.chk.stub.neither.determined.dv"),
    NUM_MISCROYALTIES_DV_CHK_STUB_NEITHER_DETERMINED_PDP("message.tax.num.miscroyalties.dv.chk.stub.neither.determined.pdp"),
    NUM_MISCOTHERINCOME_DV_CHK_STUB_INCLUSIONS_DETERMINED("message.tax.num.miscotherincome.dv.chk.stub.inclusions.determined", true),
    NUM_MISCOTHERINCOME_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("message.tax.num.miscotherincome.dv.chk.stub.inclusions.determined.dv"),
    NUM_MISCOTHERINCOME_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("message.tax.num.miscotherincome.dv.chk.stub.inclusions.determined.pdp"),
    NUM_MISCOTHERINCOME_DV_CHK_STUB_EXCLUSIONS_DETERMINED("message.tax.num.miscotherincome.dv.chk.stub.exclusions.determined", true),
    NUM_MISCOTHERINCOME_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("message.tax.num.miscotherincome.dv.chk.stub.exclusions.determined.dv"),
    NUM_MISCOTHERINCOME_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("message.tax.num.miscotherincome.dv.chk.stub.exclusions.determined.pdp"),
    NUM_MISCOTHERINCOME_DV_CHK_STUB_NEITHER_DETERMINED("message.tax.num.miscotherincome.dv.chk.stub.neither.determined", true),
    NUM_MISCOTHERINCOME_DV_CHK_STUB_NEITHER_DETERMINED_DV("message.tax.num.miscotherincome.dv.chk.stub.neither.determined.dv"),
    NUM_MISCOTHERINCOME_DV_CHK_STUB_NEITHER_DETERMINED_PDP("message.tax.num.miscotherincome.dv.chk.stub.neither.determined.pdp"),
    NUM_MISCFEDINCOMETAX_DV_CHK_STUB_INCLUSIONS_DETERMINED("message.tax.num.miscfedincometax.dv.chk.stub.inclusions.determined", true),
    NUM_MISCFEDINCOMETAX_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("message.tax.num.miscfedincometax.dv.chk.stub.inclusions.determined.dv"),
    NUM_MISCFEDINCOMETAX_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("message.tax.num.miscfedincometax.dv.chk.stub.inclusions.determined.pdp"),
    NUM_MISCFEDINCOMETAX_DV_CHK_STUB_EXCLUSIONS_DETERMINED("message.tax.num.miscfedincometax.dv.chk.stub.exclusions.determined", true),
    NUM_MISCFEDINCOMETAX_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("message.tax.num.miscfedincometax.dv.chk.stub.exclusions.determined.dv"),
    NUM_MISCFEDINCOMETAX_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("message.tax.num.miscfedincometax.dv.chk.stub.exclusions.determined.pdp"),
    NUM_MISCFEDINCOMETAX_DV_CHK_STUB_NEITHER_DETERMINED("message.tax.num.miscfedincometax.dv.chk.stub.neither.determined", true),
    NUM_MISCFEDINCOMETAX_DV_CHK_STUB_NEITHER_DETERMINED_DV("message.tax.num.miscfedincometax.dv.chk.stub.neither.determined.dv"),
    NUM_MISCFEDINCOMETAX_DV_CHK_STUB_NEITHER_DETERMINED_PDP("message.tax.num.miscfedincometax.dv.chk.stub.neither.determined.pdp"),
    NUM_MISCFISHINGBOATP_DV_CHK_STUB_INCLUSIONS_DETERMINED("message.tax.num.miscfishingboatp.dv.chk.stub.inclusions.determined", true),
    NUM_MISCFISHINGBOATP_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("message.tax.num.miscfishingboatp.dv.chk.stub.inclusions.determined.dv"),
    NUM_MISCFISHINGBOATP_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("message.tax.num.miscfishingboatp.dv.chk.stub.inclusions.determined.pdp"),
    NUM_MISCFISHINGBOATP_DV_CHK_STUB_EXCLUSIONS_DETERMINED("message.tax.num.miscfishingboatp.dv.chk.stub.exclusions.determined", true),
    NUM_MISCFISHINGBOATP_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("message.tax.num.miscfishingboatp.dv.chk.stub.exclusions.determined.dv"),
    NUM_MISCFISHINGBOATP_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("message.tax.num.miscfishingboatp.dv.chk.stub.exclusions.determined.pdp"),
    NUM_MISCFISHINGBOATP_DV_CHK_STUB_NEITHER_DETERMINED("message.tax.num.miscfishingboatp.dv.chk.stub.neither.determined", true),
    NUM_MISCFISHINGBOATP_DV_CHK_STUB_NEITHER_DETERMINED_DV("message.tax.num.miscfishingboatp.dv.chk.stub.neither.determined.dv"),
    NUM_MISCFISHINGBOATP_DV_CHK_STUB_NEITHER_DETERMINED_PDP("message.tax.num.miscfishingboatp.dv.chk.stub.neither.determined.pdp"),
    NUM_MISCMEDICALHEALT_DV_CHK_STUB_INCLUSIONS_DETERMINED("message.tax.num.miscmedicalhealt.dv.chk.stub.inclusions.determined", true),
    NUM_MISCMEDICALHEALT_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("message.tax.num.miscmedicalhealt.dv.chk.stub.inclusions.determined.dv"),
    NUM_MISCMEDICALHEALT_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("message.tax.num.miscmedicalhealt.dv.chk.stub.inclusions.determined.pdp"),
    NUM_MISCMEDICALHEALT_DV_CHK_STUB_EXCLUSIONS_DETERMINED("message.tax.num.miscmedicalhealt.dv.chk.stub.exclusions.determined", true),
    NUM_MISCMEDICALHEALT_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("message.tax.num.miscmedicalhealt.dv.chk.stub.exclusions.determined.dv"),
    NUM_MISCMEDICALHEALT_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("message.tax.num.miscmedicalhealt.dv.chk.stub.exclusions.determined.pdp"),
    NUM_MISCMEDICALHEALT_DV_CHK_STUB_NEITHER_DETERMINED("message.tax.num.miscmedicalhealt.dv.chk.stub.neither.determined", true),
    NUM_MISCMEDICALHEALT_DV_CHK_STUB_NEITHER_DETERMINED_DV("message.tax.num.miscmedicalhealt.dv.chk.stub.neither.determined.dv"),
    NUM_MISCMEDICALHEALT_DV_CHK_STUB_NEITHER_DETERMINED_PDP("message.tax.num.miscmedicalhealt.dv.chk.stub.neither.determined.pdp"),
    NUM_MISCSUBSTITUTEPA_DV_CHK_STUB_INCLUSIONS_DETERMINED("message.tax.num.miscsubstitutepa.dv.chk.stub.inclusions.determined", true),
    NUM_MISCSUBSTITUTEPA_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("message.tax.num.miscsubstitutepa.dv.chk.stub.inclusions.determined.dv"),
    NUM_MISCSUBSTITUTEPA_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("message.tax.num.miscsubstitutepa.dv.chk.stub.inclusions.determined.pdp"),
    NUM_MISCSUBSTITUTEPA_DV_CHK_STUB_EXCLUSIONS_DETERMINED("message.tax.num.miscsubstitutepa.dv.chk.stub.exclusions.determined", true),
    NUM_MISCSUBSTITUTEPA_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("message.tax.num.miscsubstitutepa.dv.chk.stub.exclusions.determined.dv"),
    NUM_MISCSUBSTITUTEPA_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("message.tax.num.miscsubstitutepa.dv.chk.stub.exclusions.determined.pdp"),
    NUM_MISCSUBSTITUTEPA_DV_CHK_STUB_NEITHER_DETERMINED("message.tax.num.miscsubstitutepa.dv.chk.stub.neither.determined", true),
    NUM_MISCSUBSTITUTEPA_DV_CHK_STUB_NEITHER_DETERMINED_DV("message.tax.num.miscsubstitutepa.dv.chk.stub.neither.determined.dv"),
    NUM_MISCSUBSTITUTEPA_DV_CHK_STUB_NEITHER_DETERMINED_PDP("message.tax.num.miscsubstitutepa.dv.chk.stub.neither.determined.pdp"),
    NUM_MISCCROPINSURANC_DV_CHK_STUB_INCLUSIONS_DETERMINED("message.tax.num.misccropinsuranc.dv.chk.stub.inclusions.determined", true),
    NUM_MISCCROPINSURANC_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("message.tax.num.misccropinsuranc.dv.chk.stub.inclusions.determined.dv"),
    NUM_MISCCROPINSURANC_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("message.tax.num.misccropinsuranc.dv.chk.stub.inclusions.determined.pdp"),
    NUM_MISCCROPINSURANC_DV_CHK_STUB_EXCLUSIONS_DETERMINED("message.tax.num.misccropinsuranc.dv.chk.stub.exclusions.determined", true),
    NUM_MISCCROPINSURANC_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("message.tax.num.misccropinsuranc.dv.chk.stub.exclusions.determined.dv"),
    NUM_MISCCROPINSURANC_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("message.tax.num.misccropinsuranc.dv.chk.stub.exclusions.determined.pdp"),
    NUM_MISCCROPINSURANC_DV_CHK_STUB_NEITHER_DETERMINED("message.tax.num.misccropinsuranc.dv.chk.stub.neither.determined", true),
    NUM_MISCCROPINSURANC_DV_CHK_STUB_NEITHER_DETERMINED_DV("message.tax.num.misccropinsuranc.dv.chk.stub.neither.determined.dv"),
    NUM_MISCCROPINSURANC_DV_CHK_STUB_NEITHER_DETERMINED_PDP("message.tax.num.misccropinsuranc.dv.chk.stub.neither.determined.pdp"),
    NUM_MISCGROSSPROCEED_DV_CHK_STUB_INCLUSIONS_DETERMINED("message.tax.num.miscgrossproceed.dv.chk.stub.inclusions.determined", true),
    NUM_MISCGROSSPROCEED_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("message.tax.num.miscgrossproceed.dv.chk.stub.inclusions.determined.dv"),
    NUM_MISCGROSSPROCEED_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("message.tax.num.miscgrossproceed.dv.chk.stub.inclusions.determined.pdp"),
    NUM_MISCGROSSPROCEED_DV_CHK_STUB_EXCLUSIONS_DETERMINED("message.tax.num.miscgrossproceed.dv.chk.stub.exclusions.determined", true),
    NUM_MISCGROSSPROCEED_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("message.tax.num.miscgrossproceed.dv.chk.stub.exclusions.determined.dv"),
    NUM_MISCGROSSPROCEED_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("message.tax.num.miscgrossproceed.dv.chk.stub.exclusions.determined.pdp"),
    NUM_MISCGROSSPROCEED_DV_CHK_STUB_NEITHER_DETERMINED("message.tax.num.miscgrossproceed.dv.chk.stub.neither.determined", true),
    NUM_MISCGROSSPROCEED_DV_CHK_STUB_NEITHER_DETERMINED_DV("message.tax.num.miscgrossproceed.dv.chk.stub.neither.determined.dv"),
    NUM_MISCGROSSPROCEED_DV_CHK_STUB_NEITHER_DETERMINED_PDP("message.tax.num.miscgrossproceed.dv.chk.stub.neither.determined.pdp"),
    NUM_MISCSECTION409AD_DV_CHK_STUB_INCLUSIONS_DETERMINED("message.tax.num.miscsection409ad.dv.chk.stub.inclusions.determined", true),
    NUM_MISCSECTION409AD_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("message.tax.num.miscsection409ad.dv.chk.stub.inclusions.determined.dv"),
    NUM_MISCSECTION409AD_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("message.tax.num.miscsection409ad.dv.chk.stub.inclusions.determined.pdp"),
    NUM_MISCSECTION409AD_DV_CHK_STUB_EXCLUSIONS_DETERMINED("message.tax.num.miscsection409ad.dv.chk.stub.exclusions.determined", true),
    NUM_MISCSECTION409AD_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("message.tax.num.miscsection409ad.dv.chk.stub.exclusions.determined.dv"),
    NUM_MISCSECTION409AD_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("message.tax.num.miscsection409ad.dv.chk.stub.exclusions.determined.pdp"),
    NUM_MISCSECTION409AD_DV_CHK_STUB_NEITHER_DETERMINED("message.tax.num.miscsection409ad.dv.chk.stub.neither.determined", true),
    NUM_MISCSECTION409AD_DV_CHK_STUB_NEITHER_DETERMINED_DV("message.tax.num.miscsection409ad.dv.chk.stub.neither.determined.dv"),
    NUM_MISCSECTION409AD_DV_CHK_STUB_NEITHER_DETERMINED_PDP("message.tax.num.miscsection409ad.dv.chk.stub.neither.determined.pdp"),
    NUM_MISCGOLDENPARACH_DV_CHK_STUB_INCLUSIONS_DETERMINED("message.tax.num.miscgoldenparach.dv.chk.stub.inclusions.determined", true),
    NUM_MISCGOLDENPARACH_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("message.tax.num.miscgoldenparach.dv.chk.stub.inclusions.determined.dv"),
    NUM_MISCGOLDENPARACH_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("message.tax.num.miscgoldenparach.dv.chk.stub.inclusions.determined.pdp"),
    NUM_MISCGOLDENPARACH_DV_CHK_STUB_EXCLUSIONS_DETERMINED("message.tax.num.miscgoldenparach.dv.chk.stub.exclusions.determined", true),
    NUM_MISCGOLDENPARACH_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("message.tax.num.miscgoldenparach.dv.chk.stub.exclusions.determined.dv"),
    NUM_MISCGOLDENPARACH_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("message.tax.num.miscgoldenparach.dv.chk.stub.exclusions.determined.pdp"),
    NUM_MISCGOLDENPARACH_DV_CHK_STUB_NEITHER_DETERMINED("message.tax.num.miscgoldenparach.dv.chk.stub.neither.determined", true),
    NUM_MISCGOLDENPARACH_DV_CHK_STUB_NEITHER_DETERMINED_DV("message.tax.num.miscgoldenparach.dv.chk.stub.neither.determined.dv"),
    NUM_MISCGOLDENPARACH_DV_CHK_STUB_NEITHER_DETERMINED_PDP("message.tax.num.miscgoldenparach.dv.chk.stub.neither.determined.pdp"),
    NUM_MISCNONQUALIFIED_DV_CHK_STUB_INCLUSIONS_DETERMINED("message.tax.num.miscnonqualified.dv.chk.stub.inclusions.determined", true),
    NUM_MISCNONQUALIFIED_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("message.tax.num.miscnonqualified.dv.chk.stub.inclusions.determined.dv"),
    NUM_MISCNONQUALIFIED_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("message.tax.num.miscnonqualified.dv.chk.stub.inclusions.determined.pdp"),
    NUM_MISCNONQUALIFIED_DV_CHK_STUB_EXCLUSIONS_DETERMINED("message.tax.num.miscnonqualified.dv.chk.stub.exclusions.determined", true),
    NUM_MISCNONQUALIFIED_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("message.tax.num.miscnonqualified.dv.chk.stub.exclusions.determined.dv"),
    NUM_MISCNONQUALIFIED_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("message.tax.num.miscnonqualified.dv.chk.stub.exclusions.determined.pdp"),
    NUM_MISCNONQUALIFIED_DV_CHK_STUB_NEITHER_DETERMINED("message.tax.num.miscnonqualified.dv.chk.stub.neither.determined", true),
    NUM_MISCNONQUALIFIED_DV_CHK_STUB_NEITHER_DETERMINED_DV("message.tax.num.miscnonqualified.dv.chk.stub.neither.determined.dv"),
    NUM_MISCNONQUALIFIED_DV_CHK_STUB_NEITHER_DETERMINED_PDP("message.tax.num.miscnonqualified.dv.chk.stub.neither.determined.pdp"),
    NUM_MISCSTATETAXWITH_DV_CHK_STUB_INCLUSIONS_DETERMINED("message.tax.num.miscstatetaxwith.dv.chk.stub.inclusions.determined", true),
    NUM_MISCSTATETAXWITH_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("message.tax.num.miscstatetaxwith.dv.chk.stub.inclusions.determined.dv"),
    NUM_MISCSTATETAXWITH_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("message.tax.num.miscstatetaxwith.dv.chk.stub.inclusions.determined.pdp"),
    NUM_MISCSTATETAXWITH_DV_CHK_STUB_EXCLUSIONS_DETERMINED("message.tax.num.miscstatetaxwith.dv.chk.stub.exclusions.determined", true),
    NUM_MISCSTATETAXWITH_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("message.tax.num.miscstatetaxwith.dv.chk.stub.exclusions.determined.dv"),
    NUM_MISCSTATETAXWITH_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("message.tax.num.miscstatetaxwith.dv.chk.stub.exclusions.determined.pdp"),
    NUM_MISCSTATETAXWITH_DV_CHK_STUB_NEITHER_DETERMINED("message.tax.num.miscstatetaxwith.dv.chk.stub.neither.determined", true),
    NUM_MISCSTATETAXWITH_DV_CHK_STUB_NEITHER_DETERMINED_DV("message.tax.num.miscstatetaxwith.dv.chk.stub.neither.determined.dv"),
    NUM_MISCSTATETAXWITH_DV_CHK_STUB_NEITHER_DETERMINED_PDP("message.tax.num.miscstatetaxwith.dv.chk.stub.neither.determined.pdp"),
    NUM_MISCSTATEINCOME_DV_CHK_STUB_INCLUSIONS_DETERMINED("message.tax.num.miscstateincome.dv.chk.stub.inclusions.determined", true),
    NUM_MISCSTATEINCOME_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("message.tax.num.miscstateincome.dv.chk.stub.inclusions.determined.dv"),
    NUM_MISCSTATEINCOME_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("message.tax.num.miscstateincome.dv.chk.stub.inclusions.determined.pdp"),
    NUM_MISCSTATEINCOME_DV_CHK_STUB_EXCLUSIONS_DETERMINED("message.tax.num.miscstateincome.dv.chk.stub.exclusions.determined", true),
    NUM_MISCSTATEINCOME_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("message.tax.num.miscstateincome.dv.chk.stub.exclusions.determined.dv"),
    NUM_MISCSTATEINCOME_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("message.tax.num.miscstateincome.dv.chk.stub.exclusions.determined.pdp"),
    NUM_MISCSTATEINCOME_DV_CHK_STUB_NEITHER_DETERMINED("message.tax.num.miscstateincome.dv.chk.stub.neither.determined", true),
    NUM_MISCSTATEINCOME_DV_CHK_STUB_NEITHER_DETERMINED_DV("message.tax.num.miscstateincome.dv.chk.stub.neither.determined.dv"),
    NUM_MISCSTATEINCOME_DV_CHK_STUB_NEITHER_DETERMINED_PDP("message.tax.num.miscstateincome.dv.chk.stub.neither.determined.pdp"),
    NUM_NECNONEMPLOYEECO_DV_CHK_STUB_INCLUSIONS_DETERMINED("message.tax.num.necnonemployeeco.dv.chk.stub.inclusions.determined", true),
    NUM_NECNONEMPLOYEECO_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("message.tax.num.necnonemployeeco.dv.chk.stub.inclusions.determined.dv"),
    NUM_NECNONEMPLOYEECO_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("message.tax.num.necnonemployeeco.dv.chk.stub.inclusions.determined.pdp"),
    NUM_NECNONEMPLOYEECO_DV_CHK_STUB_EXCLUSIONS_DETERMINED("message.tax.num.necnonemployeeco.dv.chk.stub.exclusions.determined", true),
    NUM_NECNONEMPLOYEECO_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("message.tax.num.necnonemployeeco.dv.chk.stub.exclusions.determined.dv"),
    NUM_NECNONEMPLOYEECO_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("message.tax.num.necnonemployeeco.dv.chk.stub.exclusions.determined.pdp"),
    NUM_NECNONEMPLOYEECO_DV_CHK_STUB_NEITHER_DETERMINED("message.tax.num.necnonemployeeco.dv.chk.stub.neither.determined", true),
    NUM_NECNONEMPLOYEECO_DV_CHK_STUB_NEITHER_DETERMINED_DV("message.tax.num.necnonemployeeco.dv.chk.stub.neither.determined.dv"),
    NUM_NECNONEMPLOYEECO_DV_CHK_STUB_NEITHER_DETERMINED_PDP("message.tax.num.necnonemployeeco.dv.chk.stub.neither.determined.pdp"),
    NUM_NECFEDINCOMETAXW_DV_CHK_STUB_INCLUSIONS_DETERMINED("message.tax.num.necfedincometaxw.dv.chk.stub.inclusions.determined", true),
    NUM_NECFEDINCOMETAXW_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("message.tax.num.necfedincometaxw.dv.chk.stub.inclusions.determined.dv"),
    NUM_NECFEDINCOMETAXW_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("message.tax.num.necfedincometaxw.dv.chk.stub.inclusions.determined.pdp"),
    NUM_NECFEDINCOMETAXW_DV_CHK_STUB_EXCLUSIONS_DETERMINED("message.tax.num.necfedincometaxw.dv.chk.stub.exclusions.determined", true),
    NUM_NECFEDINCOMETAXW_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("message.tax.num.necfedincometaxw.dv.chk.stub.exclusions.determined.dv"),
    NUM_NECFEDINCOMETAXW_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("message.tax.num.necfedincometaxw.dv.chk.stub.exclusions.determined.pdp"),
    NUM_NECFEDINCOMETAXW_DV_CHK_STUB_NEITHER_DETERMINED("message.tax.num.necfedincometaxw.dv.chk.stub.neither.determined", true),
    NUM_NECFEDINCOMETAXW_DV_CHK_STUB_NEITHER_DETERMINED_DV("message.tax.num.necfedincometaxw.dv.chk.stub.neither.determined.dv"),
    NUM_NECFEDINCOMETAXW_DV_CHK_STUB_NEITHER_DETERMINED_PDP("message.tax.num.necfedincometaxw.dv.chk.stub.neither.determined.pdp"),
    NUM_NECSTATETAXWITHH_DV_CHK_STUB_INCLUSIONS_DETERMINED("message.tax.num.necstatetaxwithh.dv.chk.stub.inclusions.determined", true),
    NUM_NECSTATETAXWITHH_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("message.tax.num.necstatetaxwithh.dv.chk.stub.inclusions.determined.dv"),
    NUM_NECSTATETAXWITHH_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("message.tax.num.necstatetaxwithh.dv.chk.stub.inclusions.determined.pdp"),
    NUM_NECSTATETAXWITHH_DV_CHK_STUB_EXCLUSIONS_DETERMINED("message.tax.num.necstatetaxwithh.dv.chk.stub.exclusions.determined", true),
    NUM_NECSTATETAXWITHH_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("message.tax.num.necstatetaxwithh.dv.chk.stub.exclusions.determined.dv"),
    NUM_NECSTATETAXWITHH_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("message.tax.num.necstatetaxwithh.dv.chk.stub.exclusions.determined.pdp"),
    NUM_NECSTATETAXWITHH_DV_CHK_STUB_NEITHER_DETERMINED("message.tax.num.necstatetaxwithh.dv.chk.stub.neither.determined", true),
    NUM_NECSTATETAXWITHH_DV_CHK_STUB_NEITHER_DETERMINED_DV("message.tax.num.necstatetaxwithh.dv.chk.stub.neither.determined.dv"),
    NUM_NECSTATETAXWITHH_DV_CHK_STUB_NEITHER_DETERMINED_PDP("message.tax.num.necstatetaxwithh.dv.chk.stub.neither.determined.pdp"),
    NUM_NECSTATEINCOME_DV_CHK_STUB_INCLUSIONS_DETERMINED("message.tax.num.necstateincome.dv.chk.stub.inclusions.determined", true),
    NUM_NECSTATEINCOME_DV_CHK_STUB_INCLUSIONS_DETERMINED_DV("message.tax.num.necstateincome.dv.chk.stub.inclusions.determined.dv"),
    NUM_NECSTATEINCOME_DV_CHK_STUB_INCLUSIONS_DETERMINED_PDP("message.tax.num.necstateincome.dv.chk.stub.inclusions.determined.pdp"),
    NUM_NECSTATEINCOME_DV_CHK_STUB_EXCLUSIONS_DETERMINED("message.tax.num.necstateincome.dv.chk.stub.exclusions.determined", true),
    NUM_NECSTATEINCOME_DV_CHK_STUB_EXCLUSIONS_DETERMINED_DV("message.tax.num.necstateincome.dv.chk.stub.exclusions.determined.dv"),
    NUM_NECSTATEINCOME_DV_CHK_STUB_EXCLUSIONS_DETERMINED_PDP("message.tax.num.necstateincome.dv.chk.stub.exclusions.determined.pdp"),
    NUM_NECSTATEINCOME_DV_CHK_STUB_NEITHER_DETERMINED("message.tax.num.necstateincome.dv.chk.stub.neither.determined", true),
    NUM_NECSTATEINCOME_DV_CHK_STUB_NEITHER_DETERMINED_DV("message.tax.num.necstateincome.dv.chk.stub.neither.determined.dv"),
    NUM_NECSTATEINCOME_DV_CHK_STUB_NEITHER_DETERMINED_PDP("message.tax.num.necstateincome.dv.chk.stub.neither.determined.pdp");

    public final String propKey;
    public final boolean hasTaxSourceSpecificSubStat;

    private TaxStatType(final String propKey) {
        this(propKey, false);
    }

    private TaxStatType(final String propKey, final boolean hasTaxSourceSpecificSubStat) {
        this.propKey = propKey;
        this.hasTaxSourceSpecificSubStat = hasTaxSourceSpecificSubStat;
    }

    public String getPropKey() {
        return propKey;
    }

    @Override
    public String toString() {
        return propKey;
    }
}
